### ISSUE TITLE
Could you add Gemeente Arnhem (https://www.afvalwijzer-arnhem.nl/)

### ISSUE THREAD

**Issue by pascalsaul** [pippyn/Home-Assistant-Sensor-Afvalbeheer#103]
I see Suez is listed but not Gemeente Arnhem or as generic. Could you add https://www.afvalwijzer-arnhem.nl/

https://postcodebijadres.nl/gemeente/arnhem (6800-6846)

**Comment by pippyn** [comment]
I'll have a look.

**Comment by florisi** [comment]
I live in Arnhem too.
When I open the Afvalwijzer, it links to Afvalkalender Suez.
But Suez is not working.
Or I'm doing something wrong.

**Comment by pippyn** [comment]
You can just use a config like this (random address):
```
  - platform: afvalbeheer
    wastecollector: suez
    resources:
      - restafval
    postcode: 6841AE
    streetnumber: 37
```
