### ISSUE TITLE
Is there a way to add Westerkwartier?

### ISSUE THREAD

**Issue by Palerm0** [pippyn/Home-Assistant-Sensor-Afvalbeheer#106]
Hi,
Is there a way to ad westerkwartier?
What information do you need to add this region?

Greetings
Palermo

**Comment by pippyn** [comment]
Westerkwartier uses AfvalAlert, which is already supported.
Use a config like this:
```
- platform: afvalbeheer
  wastecollector: AfvalAlert
  resources:
  - gft
  - milieuboer
  - restafval
  postcode: 9804RT
  streetnumber: 74
```
