### ISSUE TITLE
Is there a way to make a notification with the data on which one will be emptyed

### ISSUE THREAD

**Issue by jkulker** [pippyn/Home-Assistant-Sensor-Afvalbeheer#107]
Hi there,

As the title is already mentioning. Is there a way that i can create a notification with which one is getting emptyed?

**Comment by pippyn** [comment]
Hi @jkulker,

This isn't really the place for this question. As this is more of an automation question. I would advice you to read the [docs on automation](https://www.home-assistant.io/docs/automation/) and the [notify platform](https://www.home-assistant.io/integrations/notify/). If you have any trouble or questions I would recommend the [community forum](https://community.home-assistant.io/).

That being said... this should be a start for a automation for the Avalex restafval sensor. (I didn't test the code and you'll need to adjust it for your situation):
```
- alias: 'Notify: Garbage (rest)'
  trigger:
  - at: '18:30:00'
    platform: time
  condition:
  - condition: template
    value_template: "{{ state_attr('states.sensor.avalex_restafval', 'Days-until') <= 1 }}"
  action:
    service: notify.notify
    data_template:
      title: 'Restafval'
      message: 'Restafval wordt morgen opgehaald'
```
It should also be possible to make an automation using the and 'tomorrow' sensor for all waste fractions at once:
```
- alias: 'Notify: Garbage Tomorrow'
  trigger:
  - at: '18:30:00'
    platform: time
  condition:
  - condition: template.
    value_template: "{{ states('states.sensor.avalex_morgen') != 'None' }}"
  action:
    service: notify.notify
    data_template:
      title: 'Afval Notificatie'
      message: 'Morgen wordt opgehaald: {{states.sensor.avalex_morgen.state}}'
```
