### ISSUE TITLE
Berkelland not working as it should

### ISSUE THREAD

**Issue by killabeenl** [pippyn/Home-Assistant-Sensor-Afvalbeheer#113]
I have been using your plugin for a while now and it worked good.
But the last couple of weeks not al the info in popping up.
Berkelland gft and Berkelland restafval is working but Berkelland pbd and KCA is not working anymore.
I can't find the issue. If I check the afvalkalender at the website of berkelland then the info is there.

Can you check this issue?

**Comment by pippyn** [comment]
Can you share your config of the sensor please?

**Comment by killabeenl** [comment]
`sensor:
  - platform: afvalbeheer
    wastecollector: Berkelland
    resources:
      - restafval
      - gft
      - Grof tuinafval
      - Muziekvereniging Crescendo
      - pbd
      - kca
    postcode: 7161DH
    streetnumber: 16
    upcomingsensor: 1
    dateformat: '%d-%m'
    dateonly: 1
    nameprefix: 1
    builtinicons: 0
    dutch: 1`

**Comment by pippyn** [comment]
this is working for me:
```
- platform: afvalbeheer
  wastecollector: Berkelland
  resources:
    - restafval
    - gft
    - pmd
    - grof tuinafval
    - chemisch
  postcode: 7161DH
  streetnumber: 16
  upcomingsensor: 1
  dateformat: '%d-%m'
  dateonly: 1
  nameprefix: 1
  builtinicons: 0
  dutch: 1
```
