### ISSUE TITLE
can you add "Wijk bij Duurstede" as location?

### ISSUE THREAD

**Issue by Lucus123** [pippyn/Home-Assistant-Sensor-Afvalbeheer#118]
Can you add Wijk bij Duurstede as location?
Wijk bij Duurstede uses MijnAfvalwijzer as provider.
you also need 1 wastedictionary change:
pbd = pmd

**Comment by pippyn** [comment]
MijnAfvalWijzer is already supported. Use a config like so:
```
    - platform: afvalbeheer
      wastecollector: MijnAfvalWijzer
      resources: 
        - restafval
        - gft
        - papier
        - pmd
      postcode: 1111AA 
      streetnumber: 1
```
