### ISSUE TITLE
[Bug] Wrong Sort-date when state = unknown

### ISSUE THREAD

**Issue by Devqon** [pippyn/Home-Assistant-Sensor-Afvalbeheer#122]
I am using this sensor in combination with the [`auto-entities` card](https://github.com/thomasloven/lovelace-auto-entities). The method I use is order by attribute, specifically the `Sort-date` (which was added solely for this card if I remember correctly).

However, when one of the sensors reads as 'unknown', the sensor gets a `Sort-date` of 0, and thus adds it as first in the `auto-entities` card.
Configuration:
```yml
sensor:
  - platform: afvalbeheer
    wastecollector: ROVA
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 8181KA
    streetnumber: 24
    upcomingsensor: 1
    dutch: 1
```
Lovelace:
```yml
- type: 'custom:auto-entities'
  card:
    type: glance
  filter:
    include:
      - entity_id: sensor.rova_papier
      - entity_id: sensor.rova_gft
      - entity_id: sensor.rova_pmd
      - entity_id: sensor.rova_restafval
  sort:
    method: attribute
    numeric: true
    attribute: Sort-date
```
![image](https://user-images.githubusercontent.com/9316480/86463684-401cdc80-bd2e-11ea-8226-a22646901eee.png)

**Comment by pippyn** [comment]
More of a question for the auto-entities card, but i would add an [extra filter to the card](https://github.com/thomasloven/lovelace-auto-entities#filters)

example:
```
filter:
  exclude:
    - attributes:
        Sort-date: "> 0"
```

**Comment by Devqon** [comment]
Right, this indeed prevents the sensors with state `unknown` to render in the card. In my case I find this suffice/acceptable, thank you!
For others for reference, the correct notation to exclude the ones with `unknown` is as follows:
```yml
- type: 'custom:auto-entities'
  card:
    type: glance
  filter:
    include:
      - entity_id: sensor.rova_papier
      - entity_id: sensor.rova_gft
      - entity_id: sensor.rova_pmd
      - entity_id: sensor.rova_restafval
    exclude:
      - attributes:
          Sort-date: 0
  sort:
    method: attribute
    numeric: true
    attribute: Sort-date
```
