### ISSUE TITLE
Ophaalcalender belgium published a new site

### ISSUE THREAD

**Issue by geoffreylagaisse** [pippyn/Home-Assistant-Sensor-Afvalbeheer#126]
This morning we started to get ssl errors in this module because of the ophaalkalender integration.
I did some research and found that ophaalkalender.be has been replaced by https://recycleapp.be/ ...

as far as i can see the api is straightforward, yet no documentation is available yet :-(
The things I found are:

ZipID request URL: https://recycleapp.be/api/app/v1/zipcodes?q=gent

StreetID request URL: https://recycleapp.be/api/app/v1/streets?q=ved&zipcodes=9050-44021

Collections Request URL: https://recycleapp.be/api/app/v1/collections?zipcodeId={ZipId}&streetId={StreetID}&houseNumber=28&fromDate=2020-07-24&untilDate=2020-08-07&size=100

There is an authorization header required: 
Request URL: https://recycleapp.be/api/app/v1/access-token

If I find the time this weekend, I'll take a look at this new integration

**Comment by pippyn** [comment]
Thanks for the notice and your research. Would be happy to accept a pull request! If you need any help, let me know

**Comment by pippyn** [comment]
I've written some code to support RecycleApp. Are you willing to test the beta?
Replace the contents of sensor.py with the contents of [this link](https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/recycleapp/custom_components/afvalbeheer/sensor.py).
Config of the sensor should look something like this:
```
  - platform: afvalbeheer
    wastecollector: ophaalkalender
    resources:
      - restafval
    postcode: ####
    streetnumber: #
    streetname: ######
    printwastetypes: 1 #optional; this will create a persistent notification with all possible fractions for your address on restart of HA
```
