### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by realjax** [pippyn/Home-Assistant-Sensor-Afvalbeheer#129]
Hi, 

It stopped working for some reason. Just says that entities are no longer available

**Comment by pippyn** [comment]
I'll need some more info..

what is your config? what does the error log say?

**Comment by realjax** [comment]
There are no errors in the log.

The config is this:
```
sensor:
    - platform: afvalbeheer
      wastecollector: Cyclus
      resources:
        - restafval
        - gft
        - papier
        - pmd
      postcode: 1234AB
      streetnumber: 99
      upcomingsensor: 0
      dateformat: '%d-%m-%Y'
      dateonly: 0
      name: ""
      nameprefix: 1
      builtinicons: 1
      dutch: 1
```

Postcode and streetnumber are obviously not the real ones :)
