### ISSUE TITLE
Meerlanden uknown

### ISSUE THREAD

**Issue by passie** [pippyn/Home-Assistant-Sensor-Afvalbeheer#13]
I have added meerlanden as waste collector but it's not showing me any data.
```

sensor.meerlanden_gft  unknown
sensor.meerlanden_papier  unknown
sensor.meerlanden_pmd  unknown
sensor.meerlanden_restafval  unknown
```

Is this only in available in some areas?

current config looks looks like this:

```
  - platform: afvalbeheer
    wastecollector: meerlanden
    resources:                       
      - restafval
      - gft
      - papier
      - pmd
    postcode: 2131AN      
    streetnumber: 13      
    upcomingsensor: 0     
    dateformat: '%d-%m-%Y'
    dateonly: 0           
    nameprefix: 1         
    builtinicons: 0 
```

Isn't this available in my region?
