### ISSUE TITLE
Day of the week in all sensors

### ISSUE THREAD

**Issue by lolfonfire** [pippyn/Home-Assistant-Sensor-Afvalbeheer#130]
Hi,

Is there a way to show the day of the week on all sensors?
Changing "dateonly" only shows/hides weekdays on "sensor.recycleapp_restafval" and no other sensors.

![image](https://user-images.githubusercontent.com/50797554/89525318-4b0fd480-d7e6-11ea-81d1-b8c20cd192a3.png)
![image](https://user-images.githubusercontent.com/50797554/89526167-a0001a80-d7e7-11ea-9710-d058d654941b.png)

This is my config:
----------------------------
#afvalbeheer
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - papier
      - pmd
    postcode: ##MyPostalCode##
    streetname: ##MyStreetName##
    streetnumber: ##MyStreetNumber##
    upcomingsensor: 1
    dateformat: '%d-%m-%y'
    dateonly: 0
    name: ""
    nameprefix: 1
    builtinicons: 0
    dutch: 1

Thanks!

**Comment by pippyn** [comment]
add `dayofweek: 1` to your config
Example:
```
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - papier
      - pmd
    postcode: ##MyPostalCode##
    streetname: ##MyStreetName##
    streetnumber: ##MyStreetNumber##
    upcomingsensor: 1
    dateformat: '%d-%m-%y'
    dateonly: 0
    name: ""
    nameprefix: 1
    builtinicons: 0
    dutch: 1
    dayofweek: 1
```
