### ISSUE TITLE
Avalex waste type "paper" not included

### ISSUE THREAD

**Issue by danny8m8** [pippyn/Home-Assistant-Sensor-Afvalbeheer#163]
Available waste types in Afvalbeheer for provider "Avalex" is only GFT and Restafval, while their calendar also displays "Paper".

Snippet from their rest api:
,{"afvalstroom_id":138,"ophaaldatum":"2020-11-13"},{"afvalstroom_id":140,"ophaaldatum":"2020-11-20"},{"afvalstroom_id":132,"ophaaldatum":"2020-11-25"},

Where the id's are: 138 is paper, 140 is restafval and 132 is GFT. Can paper be added too?

**Comment by pippyn** [comment]
All available waste types are added by default. Did you try the function ["Print all available waste fractions"](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions)?

**Comment by danny8m8** [comment]
Yes I did, and it returns: "Available waste types: gft, restafval".
At https://www.avalex.nl/kalender you can try the example zipcode: 2631 TM, nr 1 and see that "paper" is also included in their calendar through the same way as gft and restafval.

**Comment by pippyn** [comment]
I tested with the following config:
```
sensor:
  - platform: afvalbeheer
    wastecollector: avalex
    resources:
      - gft
      - restafval
      - papier
    postcode: 2631TM
    streetnumber: 1
    printwastetypes: 1
```
And this is the result:
```
Available waste types: gft, papier, restafval
```
And the sensors are working fine
