### ISSUE TITLE
upcomingsensor is missing restafvalzakken

### ISSUE THREAD

**Issue by williamgeurts** [pippyn/Home-Assistant-Sensor-Afvalbeheer#164]
Hi,
The upcomingsensor is missing restafvalzakken in Cranendonck. The data:

sensor.restafvalzakken | Morgen, 17-11 | Wastecollector: cranendonck Hidden: false Sort-date: 20201117 Days-until: 1 unit_of_measurement:  friendly_name: restafvalzakken

sensor.gft | Morgen, 17-11 | Wastecollector: cranendonck Hidden: false Sort-date: 20201117 Days-until: 1 unit_of_measurement:  friendly_name: gft

sensor.morgen | gft | Hidden: false unit_of_measurement:  friendly_name: morgen icon: mdi:trash-can-outline

**Comment by pippyn** [comment]
Can you share you config please? With a working address in your neighborhood?

**Comment by williamgeurts** [comment]
- platform: afvalbeheer
    wastecollector: Cranendonck
    resources:
      - restafval
      - gft
      - papier
      - pmd
      - Restafvalzakken
    postcode: 6026DS
    streetnumber: 91
    upcomingsensor: 1
    dateformat: '%d-%m'
    dateonly: 0
    nameprefix: 0
    builtinicons: 0
    dutch: 1

-- 
Met vriendelijke groet,

William Geurts

**Comment by pippyn** [comment]
I'm not sure why yet, but if you change the capital R to a lower r, it's working again...
For now this is a fix, but I'll dive into it, to find the culprit.
So change your config to:
```
  - platform: afvalbeheer
    wastecollector: Cranendonck
    resources:
      - restafval
      - gft
      - papier
      - pmd
      - restafvalzakken
    postcode: 6026DS
    streetnumber: 91
    upcomingsensor: 1
    dateformat: '%d-%m'
    dateonly: 0
    nameprefix: 0
    builtinicons: 0
    dutch: 1
```
