### ISSUE TITLE
Error in Home Assistant Log - No information loaded in to the sensors.

### ISSUE THREAD

**Issue by Raffytje** [pippyn/Home-Assistant-Sensor-Afvalbeheer#166]
Hi,

I have the following error messages in the Log of Home Assistant:

`
Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:927
First occurred: November 22, 2020, 9:53:12 PM (1 occurrences)
Last logged: November 22, 2020, 9:53:12 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 437, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 949, in update
    await self.hass.async_add_executor_job(self.__fetch_address)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 927, in __fetch_address
    response = requests.get(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

My config:
`  - platform: afvalbeheer
    wastecollector: Avalex
    resources: 
      - restafval
      - gft
      - papier
    postcode: 2631CL
    streetnumber: 36
    upcomingsensor: 0
    dateformat: '%d-%m-%Y'
    dateonly: 0
    dateobject: 0
    name: ''
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 1`

I use the Stable version of the HA Docker image (https://hub.docker.com/r/homeassistant/home-assistant).

**Comment by pippyn** [comment]
when i fix the indentation and add the end of lines, it works fine:
```
sensor:
  - platform: afvalbeheer
    wastecollector: Avalex
    resources:
      - restafval
      - gft
      - papier
    postcode: 2631CL
    streetnumber: 36
    upcomingsensor: 0
    dateformat: "%d-%m-%Y"
    dateonly: 0
    dateobject: 0
    name: ""
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 1
```
