### ISSUE TITLE
Adrress not found!

### ISSUE THREAD

**Issue by Suspect-byte** [pippyn/Home-Assistant-Sensor-Afvalbeheer#171]
Hey, first of all thanks for making this! But I have a problem. The components doesn't recognize my postcode.

My logs:
```
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:963
Integration: afvalbeheer (documentation)
First occurred: 8:25:05 PM (1 occurrences)
Last logged: 8:25:05 PM

No Waste data found!
```

```
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:934
Integration: afvalbeheer (documentation)
First occurred: 8:25:04 PM (1 occurrences)
Last logged: 8:25:04 PM

Address not found!
```

here is my config:
```
  - platform: afvalbeheer
    wastecollector: ZRD
    resources:
      - restafval
      - gft
      - papier
    postcode: *
    streetnumber: *
    upcomingsensor: 0
    dateformat: "%d-%m-%Y"
    dateonly: 0
    dateobject: 0
    name: ""
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 1
```

Thanks in advance for looking at problem. Hopefully you can help me.
