### ISSUE TITLE
Suez isn't working

### ISSUE THREAD

**Issue by 19jm81** [pippyn/Home-Assistant-Sensor-Afvalbeheer#172]
Keep getting the message unknown, my config is this:

# Afval sensor
    
  - platform: afvalbeheer
    wastecollector: Suez            
    resources:                     
    - restafval
    - gft
    - papier
    - pmd
    postcode: 6811BW                 
    streetnumber: 5

**Comment by pippyn** [comment]
The indentation is wrong...
It should be something like:
```
  - platform: afvalbeheer
    wastecollector: Suez
    - resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: 6811BW
    streetnumber: 5
```

**Comment by 19jm81** [comment]
Including this? 
    - resources:
This gives an indentation error

**Comment by pippyn** [comment]
No I'm sorry, like this:
```
  - platform: afvalbeheer
    wastecollector: Suez
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: 6811BW
    streetnumber: 5
```

**Comment by 19jm81** [comment]
I do get this in the logs (got that already before submitting issue):

Could the adresses be invalid? Do I need to add floor number?

Afvalinfo Eusebiusbinnensingel Tomorrow changed to none
8:42:15 AM - 4 minutes ago

But my dashboard:

type: entities
entities:
  - entity: sensor.afvalinfo_eusebiusbinnensingel_gft
  - entity: sensor.afvalinfo_eusebiusbinnensingel_papier
  - entity: sensor.afvalinfo_eusebiusbinnensingel_pbd
  - entity: sensor.afvalinfo_eusebiusbinnensingel_restafval
  - entity: sensor.afvalinfo_eusebiusbinnensingel_textiel
  - entity: sensor.afvalinfo_eusebiusbinnensingel_today
  - entity: sensor.afvalinfo_eusebiusbinnensingel_tomorrow

Keeps saying:

Afvalinfo Eusebiusbinnensingel GFT
Unknown
Afvalinfo Eusebiusbinnensingel Papier
Unknown
Afvalinfo Eusebiusbinnensingel PBD
Unknown
Afvalinfo Eusebiusbinnensingel Restafval
Unknown
Afvalinfo Eusebiusbinnensingel Textiel
Unknown
Afvalinfo Eusebiusbinnensingel Today
none
Afvalinfo Eusebiusbinnensingel Tomorrow
non

**Comment by pippyn** [comment]
You can use a suffix like so:
No I'm sorry, like this:
```
  - platform: afvalbeheer
    wastecollector: Suez
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: 6811BW
    streetnumber: 5
    suffix: A
```
