### ISSUE TITLE
sensor.areareiniging_restafval unknown

### ISSUE THREAD

**Issue by wilfredsmit** [pippyn/Home-Assistant-Sensor-Afvalbeheer#173]
The restafval sensor is currently unknown.

**Comment by pippyn** [comment]
Well.. i would need some more info??
What's your config? Did it work before? Does the website give you the correct information? Do you have any errors in the HA log?

**Comment by wilfredsmit** [comment]
Installed through HACS. It used to work. Looks like the 2021 calendar isn't online yet at AreaReiniging. I suppose that is the issue.

```
sensor:
  - platform: afvalbeheer
    wastecollector: AreaReiniging
    resources:
      - gft
      - restwagen
      - restafval
      - pmd
    postcode: 7908ML
    streetnumber: 61
    upcomingsensor: 1
    printwastetypes: 1
    dateformat: '%d %B %Y'
    dateonly: 0
    dateobject: 0
    alwaysshowday: 1
    name: ''
    nameprefix: 1
    builtinicons: 1
    disableicons: 0
    dutch: 1
```
