### ISSUE TITLE
Config not correct?

### ISSUE THREAD

**Issue by dennidoubles** [pippyn/Home-Assistant-Sensor-Afvalbeheer#175]
Good afternoon, pretty new with HA , but I hope you are willing to help me out.
I really would like to have this integration, but I don't seem to be able to have it work properly. 
We live in Blaricum, so I changed this in the basic config.
Anyway, I installed via HACS, the components are in the correct directory and I placed the basic configuration in my configuration.yml 

Now I get this warning:

can not read a block mapping entry; a multiline key may not be an implicit key at line 83, column 15:
          dateonly: 0                      (optional)
                  ^

Could you please help me out? This is what I've placed in my config file:

sensor:
    - platform: afvalbeheer
      wastecollector: GAD              (required)
      resources:                              (at least 1 required)
        - restafval
        - gft
        - papier
        - pmd
      postcode: 1261ZC                 (required)
      streetnumber: 9                     (required)
      upcomingsensor: 1                (optional)
      dateformat: '%d-%m-%Y'      (optional)
      dateonly: 0                            (optional)
      dateobject: 0                         (optional)
      name: ''                                 (optional)
      nameprefix: 1                        (optional)
      builtinicons: 0                       (optional)
      disableicons: 0                      (optional)
      dutch: 1                                (optional)

![image](https://user-images.githubusercontent.com/71798417/102619689-1ec57680-413d-11eb-8c01-493cc05a1ae8.png)

**Comment by pippyn** [comment]
remove all the stuff inside the brackets, including the brackets
```
sensor:
- platform: afvalbeheer
  wastecollector: GAD 
  resources:
  - restafval
  - gft
  - papier
  - pmd
  postcode: 1261ZC
  streetnumber: 9
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 0
  dateobject: 0
  name: ''
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 1

```
