### ISSUE TITLE
Could you add IOK.be?

### ISSUE THREAD

**Issue by davidw3591** [pippyn/Home-Assistant-Sensor-Afvalbeheer#178]
Hi,

Would it be possible to add [https://iok.be/afvalkalender](https://iok.be/afvalkalender)?
Testadres: Turnhout, Wezenstraat

Kind regards,
David

**Comment by pippyn** [comment]
You can use the `ophaalkalender.be` for your address.
Example:
```
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - gft
      - kerstbomen
      - kga
      - papier
      - pmd
      - restafval
      - textiel
    postcode: 2300
    streetname: Wezenstraat
    streetnumber: 1
    upcomingsensor: 1
    dateobject: 1
    name: Ophaalkalender
    nameprefix: 0
    disableicons: 1
    dutch: 1
    printwastetypes: 1
```
