### ISSUE TITLE
RecycleApp API "Invalid response from server for accessToken"

### ISSUE THREAD

**Issue by stefdewilde** [pippyn/Home-Assistant-Sensor-Afvalbeheer#190]
Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1130
Integration: afvalbeheer (documentation)
First occurred: 7:02:21 AM (1 occurrences)
Last logged: 7:02:21 AM

Invalid response from server for accessToken

config:
```
#afvalbeheer sensor
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - papier
      - pmd
    postcode: 8920
    streetnumber: 121
    streetname:  Boezingestraat
    upcomingsensor: 1
    dateformat: '%d %B'
    builtinicons: 1
    dutch: 1
    nameprefix: 0
```
