### ISSUE TITLE
DAR

### ISSUE THREAD

**Issue by webmedianijmegen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#192]
# Dar begin
sensor: 
- platform: afvalbeheer
    wastecollector: dar            
    resources:                       
    - restafval
    - gft
    - papier
    - pmd
    postcode: here                 
    streetnumber: here                  
    upcomingsensor: 0                
    dateformat: '%d-%m-%Y'           
# Dar end

After i will save i get a error: 

bad indentation of a mapping entry at line 23, column 19:
        wastecollector: dar            
                      ^

**Comment by pippyn** [comment]
well as the error message says, your indentation is wrong. I can't see your indentation correctly but I guess it's something like this:
```
- platform: afvalbeheer
    wastecollector: dar            
    resources:                       
    - restafval
    - gft
    - papier
    - pmd
    postcode: here                 
    streetnumber: here                  
    upcomingsensor: 0                
    dateformat: '%d-%m-%Y' 
```
and it should be:
```
  - platform: afvalbeheer
    wastecollector: dar            
    resources:                       
    - restafval
    - gft
    - papier
    - pmd
    postcode: here                 
    streetnumber: here                  
    upcomingsensor: 0                
    dateformat: '%d-%m-%Y' 
```
