### ISSUE TITLE
How to change title?

### ISSUE THREAD

**Issue by YvoTuk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#199]
I'm a noob with homeassistant, so may be a dumb question..

I've installed the Afvalbeheer addon and everything seems to be working fine.. the only thing is.. it shows up in my dashboard as "Sensor".

Is there any way I can change that title to something more appropriate?

**Comment by leonkielstra** [comment]
I don't know how you set it up exactly (what type of card are you using?), but here is my config. Maybe it helps:

```yml
type: entities
entities:
  - entity: sensor.meerlanden_restafval
    name: Trash
    icon: 'mdi:trash-can-outline'
  - entity: sensor.meerlanden_papier
    name: Paper
    icon: 'mdi:newspaper-variant-outline'
  - entity: sensor.meerlanden_pmd
    name: Recycling
    icon: 'mdi:recycle'
title: Trash Pickup
```

Which looks like this:
<img width="503" alt="Screenshot 2021-02-12 at 18 29 11" src="https://user-images.githubusercontent.com/8023699/107801341-3a758380-6d60-11eb-8b97-d8e514a5e0b8.png">
