### ISSUE TITLE
RecycleApp not working anymore

### ISSUE THREAD

**Issue by sverleysen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#201]
The RecycleApp integration is not working for me anymore.
It worked for a few months, but since around 2 weeks it doesn't update anymore.

**Comment by pippyn** [comment]
Some more information would be helpful:
- Did it work before?
- Any errors in your log?
- What's your config?
- Please provide an address in your neighborhood

**Comment by sverleysen** [comment]
No errors in my logs

My config:
platform: afvalbeheer
wastecollector: RecycleApp
resources:
  - groente-, fruit-, en tuinafval
  - papier
  - pmd
  - restafval
postcode: 2040
streetname: Putsebaan
streetnumber: 1
upcomingsensor: 1
dateformat: '%d-%m-%Y'
dateonly: 1
dateobject: 0
printwastetypes: 1
# name: ''
nameprefix: 0
builtinicons: 0
disableicons: 0
dutch: 1

I changed the address to a different location in my neighborhood.

On startup no resources are logged in the notification.

**Comment by pippyn** [comment]
You can view your log in configuration>logs, something like (depending on your setup):
hassio.local:8123/config/info

I can see that the fraction `groente-, fruit-, en tuinafval` isn't working. I'll write a fix for that.
But the other fractions are working fine for me.

**Comment by pippyn** [comment]
In the new v4.7.13 version this config is working fine for me (note the renamed fraction gft) :
```
sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - gft
      - papier
      - pmd
      - restafval
    postcode: 2040
    streetname: Putsebaan
    streetnumber: 1
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    dateonly: 1
    dateobject: 0
    printwastetypes: 1
    # name: ''
    nameprefix: 0
    builtinicons: 0
    disableicons: 0
    dutch: 1
```
