### ISSUE TITLE
Recycle app

### ISSUE THREAD

**Issue by thecobra666** [pippyn/Home-Assistant-Sensor-Afvalbeheer#225]
I get the following error:

 Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1143
Integration: afvalbeheer (documentation)
First occurred: 14:15:44 (1 occurrences)
Last logged: 14:15:44

Invalid response from server for collection data

The sensors are created, but it's not pulling data. Probably I have a fault in the sensor config. My street is in 2 words, is that an issue?
```
  - platform: afvalbeheer
    wastecollector: RecycleApp           
    resources:
     - restafval
     - gft
     - papier
     - pmd
    postcode: 9030
    streetnumber: **
    streetname:  straat
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    nameprefix: 1
    builtinicons: 1
    dutch: 1
```
