### ISSUE TITLE
RecycleApp no longer working?

### ISSUE THREAD

**Issue by TheGroundZero** [pippyn/Home-Assistant-Sensor-Afvalbeheer#229]
Hi

The RecycleApp source no longer seems to be working.

Since a week or two the sensors have become unavailable.

```yaml
- platform: afvalbeheer
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
  postcode: 1234
  streetname: MyStreetName
  streetnumber: 69
  upcomingsensor: 0
  dateformat: '%Y-%m-%d'
  dateobject: 0
  dateonly: 1
  dayofweek: 0
  alwaysshowday: 0
  name: ''
  nameprefix: 0
  builtinicons: 1
  disableicons: 0
  dutch: 1
```

![image](https://user-images.githubusercontent.com/2406013/117136162-85b79500-ad97-11eb-8722-eba56ac3c26b.png)

**Comment by Ryckie** [comment]
I have the same issue. I copiëd over the same exact street name and so over from the app to Home Assistant. And it's showing ''Unknown''. And eye icon instead of the icons from the example screenshot.

**Comment by pippyn** [comment]
The recycleapp API has issues at the moment. Are there Amy errors in the log?

**Comment by TheGroundZero** [comment]
> The recycleapp API has issues at the moment. Are there any errors in the log?

For the moment it appears to be working again

**Comment by pippyn** [comment]
Can this issue be closed?

**Comment by Ryckie** [comment]
> Can this issue be closed?

For me it is still not showing correctly.
![image](https://user-images.githubusercontent.com/63733138/118406375-1b96ce00-b67c-11eb-8345-e8ae2a17985b.png)

**Comment by Ryckie** [comment]
```
2021-05-19 13:20:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 438, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1138, in update
    await self.hass.async_add_executor_job(self.__get_location_ids)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 1107, in __get_location_ids
    self.postcode_id = response.json()['items'][0]['id']
IndexError: list index out of range
```

**Comment by pippyn** [comment]
@Ryckie What is your config?

**Comment by Ryckie** [comment]
> @Ryckie What is your config?

This is my sensors.yaml

```
- platform: afvalbeheer
  wastecollector: RecycleApp
  printwastetypes: 1
  resources:
    - RESTAFVAL
    - gft
    - papier
    - pmd
  postcode: "0000 cityname"
  streetnumber: 5
  streetname: "my streetname"
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dayofweek: 1
  alwaysshowday: 1
  dateonly: 0
  dateobject: 0
  name: ""
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 1
  updateinterval: 1
```

**Comment by pippyn** [comment]
Does your address work on the RecycleApp.be website?
If so: Can you DM me your address on the HA forum?

**Comment by Ryckie** [comment]
> Does your address work on the RecycleApp.be website?
Yes this works, only difference there from the android app is on that site I put my postcode "0000 - cityname" In the app it's "0000 cityname". Im now testing with the "-" inbetween. Is it supposed to update the sensors on a ha restart, or does it wait for the default update time of 1 hour?

> If so: Can you DM me your address on the HA forum?
If the above doesn't solve it I will DM you there. Is this you? https://community.home-assistant.io/u/pippyn


Strange thing is that "today, tomorrow" show 'none' instead of 'unknown'. However that is also not correct and has never changed to something else then 'none'.

**Comment by pippyn** [comment]
It will update on restart (and every hour).
You have an error in your config, the postcode and cityname are 2 separate entries. And for RecycleApp cityname is not required (streetname is though).
example:
```
- platform: afvalbeheer
  wastecollector: RecycleApp
  printwastetypes: 1
  resources:
    - RESTAFVAL
    - gft
    - papier
    - pmd
  postcode: 0000
  streetnumber: 5
  streetname: "my streetname"
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dayofweek: 1
  alwaysshowday: 1
  dateonly: 0
  dateobject: 0
  name: ""
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 1
  updateinterval: 1
```
Yes that's me.

The today and tomorrow sensors get their info from the other sensors and default to 'none'. So that's normal.

**Comment by pippyn** [comment]
@Ryckie I did some tests and found that the way your address code gets pulled is different than the normal recycleapp way. I'll have a look if I can add this in the next update.

**Comment by Ryckie** [comment]
> @Ryckie I did some tests and found that the way your address code gets pulled is different than the normal recycleapp way. I'll have a look if I can add this in the next update.

Okay, thank you a lot. I hope you can get it to work.
Also, please keep my adres private (foryoureyesonly) :).

**Comment by Ryckie** [comment]
Bump

**Comment by JeroenTuinstra** [comment]
I would like to add that the recycple App in Belgium no longer works. The engineers of the app have decided in their great wisdom that they don't provide the information anymore. Apparently there is some new scheduling (don't ask me why it would work) but normally the app would say what time the garbage would be collected. Now it says what time you should set the garbage at the street. 
The difference; collection would be on Monday morning, but garbage should be set to the street after 18:00 in the evening the previous day. I am not sure where this new schedule is published, but so far only on their website and no longer in the app.

![IMG_1930](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/47460053/41f6a852-49cf-491c-83e5-c7438632cbd1)

![IMG_1930](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/47460053/0bfe9014-4c00-498b-ab46-a6d2872148aa)

The new calanders are only available through their website; [https://www.arp-gan.be/en/calendar-rubbish-bags](https://www.arp-gan.be/en/calendar-rubbish-bags) (nice and easy website to remember.  

This is really Brussels at its dumbest. They have an agreement to provide all information transparently and open for all technicians and apps to freely use the information - however moving it over to a complete different website because of a technical detail (drop off instead of collection for whatever reason they think that is more useful for Brusselaers). 

So Brussels is completely excluded from the Recycle App (something they setup themselves). I anyone is able to use the api of the new website to integrate again with Afvalbeheer - that would be greatly appreciated.

**Comment by pippyn** [comment]
@JeroenTuinstra do you have an address for me to test with?

**Comment by JeroenTuinstra** [comment]
This is the whole configuration: 
```
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
  postcode: 1000
  streetnumber: 61
  streetname: "Minimenstraat"
  printwastetypes: 0
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 0
  dayofweek: 1
  name: ""
  nameprefix: 0
  builtinicons: 1
  dutch: 0
```
All states of the sensor are unavailable.
