### ISSUE TITLE
Spaarnelanden not working

### ISSUE THREAD

**Issue by woutf** [pippyn/Home-Assistant-Sensor-Afvalbeheer#231]
I'm trying to get your sensor working, but I'm failing. I installed it through HACS and added the following to my config
```
sensor:
  - platform: afvalbeheer
    wastecollector: spaarnelanden           
    resources:                       
      - restafval
      - gft
      - papier
      - pmd
    postcode: XXXXX                
    streetnumber: XX                
    upcomingsensor: 1
    printwastetypes: 1
```
Spaarnelanden is listed as one of the available providers, but HA isn't showing any usable sensors. I get 'sensor.spaarnelanden_restafval' with a value of 'unknown'. And 'printwastetypes' returns nothing on startup.
