### ISSUE TITLE
MaxRetryError

### ISSUE THREAD

**Issue by alexborro** [pippyn/Home-Assistant-Sensor-Afvalbeheer#232]
Since a few days ago I started getting this error in my log and all the entities show as "Unknown":

Error occurred while fetching data:
 
```
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='wasteapi.ximmio.com', port=443): Max retries exceeded with url: /api/GetCalendar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f97c225b0>: Failed to establish a new connection: [Errno 110] Operation timed out'))"))
```
I set the update interval to a large value like 48h because I thought it was caused by too many connections, but it didnt solve the problem.

I'm running the latest HA and this is my config (I have 2 of it, for 2 different zip codes):

```
  - platform: afvalbeheer
    wastecollector: Avri
    resources:
      - gft
      - papier
      - pmd
    postcode: 1234AB
    streetnumber: 2
    upcomingsensor: 1
    dateformat: "%d %b" # "%d-%m-%Y"
    dateonly: 0
    dateobject: 0
    name: ""
    nameprefix: 1
    builtinicons: 1
    disableicons: 0
    dutch: 0
    printwastetypes: 0
    dayofweek: 1
    alwaysshowday: 1
    updateinterval: 47
```

If I restart the HA, sometimes it can get the data, but after some time (depending on the update interval) it get back to "Unknown"

Cheers.

Alex.
