### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by mvanmael** [pippyn/Home-Assistant-Sensor-Afvalbeheer#239]
I added the sample config to my configuration.yaml, but always obtain the following error:
sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: postcode
    cityname: city
    streetname: straat
    streetnumber: nummer
    upcomingsensor: 1
    dateformat: '%d %b
    dateonly: 0
    dateobject: 0
    name: 'Ivago'
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 1

![2021-07-12 18_06_29-File editor - Home Assistant](https://user-images.githubusercontent.com/84506059/125320430-fcdf4b80-e33b-11eb-9400-3334c7102739.png)

What's the remedy?
Thx.

**Comment by pippyn** [comment]
You are missing a close quote in the dateformat line. This config should work:

```
sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: postcode
    cityname: city
    streetname: straat
    streetnumber: nummer
    upcomingsensor: 1
    dateformat: '%d %b'
    dateonly: 0
    dateobject: 0
    name: 'Ivago'
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 1
```
