### ISSUE TITLE
Fix voor Suez (o.a. Arnhem)

### ISSUE THREAD

**Issue by victorclaessen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#244]
In Arnhem heet Suez tegenwoordig Prezero. De afvalkalender-website lijkt op een nieuwe URL na ongewijzigd. 

Als ik in `sensor.py` de URL wijzig, dan doet hij het weer:

 ```
'suez': 'https://inzamelwijzer.prezero.nl',
```

(met config:)

```
- platform: afvalbeheer
  wastecollector: Suez
  resources:
    - gft
    - papier
    - pmd
    - textiel
  postcode: 6811 DG
  streetnumber: 38
  upcomingsensor: 1
  dateformat: '%d-%m'
  dutch: 1
```

Ik wil daar best een pull-request van maken, maar ik weet niet of er verder in de code nog iets gewijzigd zou moeten worden om het netjes te houden?
