### ISSUE TITLE
State remains at day of week only while next collection is in 26 days

### ISSUE THREAD

**Issue by FredericMa** [pippyn/Home-Assistant-Sensor-Afvalbeheer#254]
I noticed that the state of the paper collection remained at 'Donderdag' while it is collected in 26 days.
I have `dayofweekonly` set to `1`.
It looks like it is caused by `self.date_format` being set to `%A`but not being reset to the configured `dateformat` on the next collection date:
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/34dc6eddb632efc8eef0d944407139ccf5772715/custom_components/afvalbeheer/sensor.py#L1392
`dayofeek` seems to suffer the same issue if I look at the code.

![image](https://user-images.githubusercontent.com/7840263/135728641-0e633478-e41d-456b-8653-d86eb8545b26.png)

**Comment by pippyn** [comment]
This is the intended function of `dayofweekonly`. This setting only reports the name of the day for the collection date. `dayofweekonly` is dependent on `dayofweek`, so:  if `dayofweek` is off, `dayofweekonly` won't work.

October 28 is a Thursday, so the state is correct.

**Comment by FredericMa** [comment]
Sure, this is my config: 
```yaml
sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - gft
      - papier
      - pmd
      - grofvuil
    postcode: 2845
    streetname: Luc Van Lindenlaan
    streetnumber: 8
    upcomingsensor: 1
    dutch: 1
    disableicons: 1
    dateonly: 0
    dateformat: '%#d/%#m'
    dayofweekonly: 1
```

Indeed the state is correct but I would expect this code to be executed now:
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/34dc6eddb632efc8eef0d944407139ccf5772715/custom_components/afvalbeheer/sensor.py#L1387-L1388

I restarted my HA instance this morning and now the state is showing as I expected:
![image](https://user-images.githubusercontent.com/7840263/135822419-778b0eb0-19df-4cee-85e4-6c3ab47e06dc.png)
