### ISSUE TITLE
If nameprefix: 0 is used I get error "Entiteit niet beschikbaar"

### ISSUE THREAD

**Issue by HansieNL** [pippyn/Home-Assistant-Sensor-Afvalbeheer#258]
I wanna use nameprefix: 0 in a mijnafvalwijzer configuration. If I use nameprefix: 0 I get the error "Entiteit niet beschikbaar".
Postcode and housenumber are fictief. Everything works well if I comment out name and nameprefix.
I use the following config:
```
sensor:
  - platform: afvalbeheer
    wastecollector: mijnafvalwijzer
    resources:
      - restafval
      - gft
      - papier
    postcode: 0000AA
    streetnumber: 11
    name: ""
    nameprefix: 0
    dayofweek: 1
    dayofweekonly: 1
    builtinicons: 0
    dutch: 1
    updateinterval: 12
```
Can you tell me what's going wrong?
