### ISSUE TITLE
gft sensor not working

### ISSUE THREAD

**Issue by WesleyLiekens** [pippyn/Home-Assistant-Sensor-Afvalbeheer#261]
hello, the sensor for gft states "onbekend" (unknown)
Could you help me out with this please?
this is my config
```
sensor:
  - platform: afvalbeheer
    wastecollector: Limburg.NET
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: 3560
    cityname: lummen
    streetname: hoekstraat
    streetnumber: 6
    upcomingsensor: 1
    dateformat: '%d-%m-%Y'
    dateonly: 0
    dayofweekonly: 0
    alwaysshowday: 1
    dayofweek: 1
    dateobject: 0
    name: 'Afval'
    nameprefix: 1
    builtinicons: 1
    disableicons: 0
    dutch: 1
```

thanks in advance
