### ISSUE TITLE
Add option to use mdi icons

### ISSUE THREAD

**Issue by Ernst79** [pippyn/Home-Assistant-Sensor-Afvalbeheer#28]
The current implementation only allows to use the build in icons or the icons from the waste collector. Both are not really in the same style as the common icons in home assistant. Overwriting the icons in ‘customize entities’ with standard mdi icons is also not working. Is it possible to add this, to just use the customize entities option of home assistant for changing icons?

**Comment by pippyn** [comment]
You can use what ever icon you want with the built-in feature of HA. Add an entry for the sensor you want to change the icon of in the customize section. ([see docs](https://www.home-assistant.io/docs/configuration/customizing-devices/))
something like;

```
homeassistant:
  customize:
    sensor.cure_gft:
      icon: mdi:fruit-watermelon
```

**Comment by Ernst79** [comment]
I did that, but it won't change the icon. I changed the icon in the customization menu, but that does basically the same, it adds yaml code to customize.yaml. I checked the files and I have the following lines in my customize.yaml (amongst others)

```
sensor.dar_gft:
  friendly_name: Gft-afval
  icon: mdi:fruit-watermelon
```

and this in configuration.yaml
```
homeassistant:
  customize: !include customize.yaml
```

Changing icons for other sensors works fine, but not for the Afval-beheer sensors. 
Does it change the icons on your home assistant?

**Comment by pippyn** [comment]
And `builtinicons` equals 0 in your config? What icons do you see? The default eye icon?

> Does it change the icons on your home assistant?

Yes

**Comment by Ernst79** [comment]
I had `builtinicons: 1`, but also with `builticons: 0` I don't get the mdi icon. With` builtinicons: 0` I get the following icons

![image](https://user-images.githubusercontent.com/24375847/71964395-c9c77380-31fd-11ea-9162-5b46696f98db.png)

**Comment by pippyn** [comment]
My bad, I will write a fix. Are you willing to test a beta version in a couple of minutes?

**Comment by Ernst79** [comment]
yes, sure. Looks like something with the picture_entity overruling the icon.

**Comment by pippyn** [comment]
Can you replace the contents of sensor.py in /custom_components/afvalbeheer/ with the code in this link: https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/master/custom_components/afvalbeheer/sensor.py

Then add the option `disableicons: 1` in your config like so:
```
 - platform: afvalbeheer
   wastecollector: Blink
   resources:
     - restafval
     - gft
     - papier
     - pmd
   postcode: 1111AA
   streetnumber: 1
   builtinicons: 0
   disableicons: 1
```
And restart

**Comment by Ernst79** [comment]
No, still the same behavior. I noticed that the "entity_picture" is always put back after restarting Home Assistant in the customization menu. 

![image](https://user-images.githubusercontent.com/24375847/71972653-5d547080-320d-11ea-8b8f-0d77e1dab254.png)

**Comment by pippyn** [comment]
I know `entity_picture` is the cause of this problem and my beta code disables this.

Do you have an entry in your "developer-tools" -> "logs" in the line of "invalid entry...."?
If so; 
- remove the line `disableicons: 1` from your config
- restart HA
- readd the line
- restart HA

BTW: Those are the builtin icons in your last post. So you don't have builtinicons: 0 in your config

**Comment by Ernst79** [comment]
My config is 

```
- platform: afvalbeheer
  wastecollector: DAR
  resources:
    - gft
    - papier
    - pmd
  postcode: 6641XG
  streetnumber: 9
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 0
  nameprefix: 1
  builtinicons: 0
   disableicons: 1
  dutch: 1
```
