### ISSUE TITLE
No Waste data found

### ISSUE THREAD

**Issue by Flash3dee** [pippyn/Home-Assistant-Sensor-Afvalbeheer#282]
Had the integration working without problem for some months but now i'm getting the following two errors in my HA log:
Using v4.9.0

No Waste data found!
08:48:05 – (ERROR) afvalbeheer (custom integration)
Address not found!
08:48:05 – (ERROR) afvalbeheer (custom integration)

Using Meerlanden as my waste collector and the following yaml config:

```
   - platform: afvalbeheer
    wastecollector: Meerlanden
    resources:                     
      - restafval
      - gft
      - pmd
    postcode: XXXXAB
    streetnumber: 12
    upcomingsensor: 1                
    dateformat: '%d-%m-%Y'           
    dateonly: 0                      
    dateobject: 0                    
    name: ''                         
    nameprefix: 1                    
    builtinicons: 0                  
    disableicons: 0                  
    dutch: 0
```
