### ISSUE TITLE
After HACS and integration update, unknown state is returned.

### ISSUE THREAD

**Issue by base2006** [pippyn/Home-Assistant-Sensor-Afvalbeheer#284]
After I updated HACS and this repo today the sensors are returning an 'unknown' state and I have no idea why. 

Any suggestions on how to solve this?

This is in my yaml file:
```yaml
- platform: afvalbeheer
  wastecollector: MijnAfvalwijzer
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: MYZIP
  streetnumber: 00
  upcomingsensor: 1
  dateformat: "%a %-d %b"
  dateonly: 0
  dateobject: 0
  name: ""
  nameprefix: 1
  builtinicons: 1
  disableicons: 0
  dutch: 0

```

![image](https://user-images.githubusercontent.com/12198035/148679080-d2f2bef6-944f-4e8f-98fd-5bda754ec456.png)
