### ISSUE TITLE
Entity sensor.circulus_berkel_gft (<class 'custom_components.afvalbeheer.sensor.WasteTypeSensor'>) implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by Zydell** [pippyn/Home-Assistant-Sensor-Afvalbeheer#285]
Since a week or so all waste sensors report 'unknown'; worked fine before; got a log to make a report.

**configuration.yaml**
```
  # afval
  - platform: afvalbeheer
    wastecollector: Circulus-Berkel
    resources:
    - gft
    - papier
    - pmd
    postcode: ------
    streetnumber: --
    upcomingsensor: 1
    builtinicons: 1
    dutch: 1
```

**logs**
```
 Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549

    Entity sensor.circulus_berkel_gft (<class 'custom_components.afvalbeheer.sensor.WasteTypeSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.circulus_berkel_papier (<class 'custom_components.afvalbeheer.sensor.WasteTypeSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.circulus_berkel_pmd (<class 'custom_components.afvalbeheer.sensor.WasteTypeSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.circulus_berkel_vandaag (<class 'custom_components.afvalbeheer.sensor.WasteDateSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.circulus_berkel_morgen (<class 'custom_components.afvalbeheer.sensor.WasteDateSensor'>) implements device_state_attributes. Please report it to the custom component author.
```
