### ISSUE TITLE
PreZero gives no results

### ISSUE THREAD

**Issue by fantastrick** [pippyn/Home-Assistant-Sensor-Afvalbeheer#288]
It worked, but now for a while there are no results from PreZero here. Is it just me or something else?

**Comment by pippyn** [comment]
Does the website of PreZero work for you?
If so, what is your config?

**Comment by fantastrick** [comment]
Yes it works

#afvalbeheer
  - platform: afvalbeheer
    wastecollector: PreZero
    resources:
      - gft
      - restafval
      - pmd
    postcode: XXXXAA
    streetnumber: XX
    upcomingsensor: 1
    dateformat: ‘%d-%m-%Y’
    dateonly: 0
    dateobject: 0
    dayofweek: 1
    name: ‘’
    nameprefix: 0
    builtinicons: 0
    disableicons: 0

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by fantastrick** [comment]
Yep, you can try with 6591AA
Thanks!

**Comment by pippyn** [comment]
there are no collection dates for 6591 BA number 3...
https://inzamelwijzer.prezero.nl/adres/6591BA:3

**Comment by fantastrick** [comment]
crap, with this one works:
https://inzamelwijzer.prezero.nl/adres/6591TN:01

**Comment by fantastrick** [comment]
<img width="383" alt="Schermafbeelding 2022-01-13 om 09 38 51" src="https://user-images.githubusercontent.com/58150260/149295313-aa0ba114-d905-432e-aef4-6fa5fdac048a.png">

This is what I am getting.... weird...

**Comment by pippyn** [comment]
with the same address?
I used this config:
```
  - platform: afvalbeheer
    wastecollector: PreZero
    resources:
      - gft
      - restafval
      - pmd
    postcode: 6591TN
    streetnumber: 1
    upcomingsensor: 1
    dateformat: ‘%d-%m-%Y’
    dateonly: 0
    dateobject: 0
    dayofweek: 1
    nameprefix: 0
    builtinicons: 0
    disableicons: 0
    printwastetypes: 1
    name: "PreZero"
```
