### ISSUE TITLE
Noob trying to install

### ISSUE THREAD

**Issue by Moossie72** [pippyn/Home-Assistant-Sensor-Afvalbeheer#295]
Hey guys,

I'm new to HA and installed 'Afvalbeheer' through Hash. but somehow I don't see my sensor. Can anyone help me with this?

Attached is the file that was created automatically in /config/custom_components/afvalbeheer/sensor.py
[Afvalbeheer.txt](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/files/7944599/Afvalbeheer.txt)

Gr, Alex

**Comment by ymoona** [comment]
I did the same, works like a charm for me. 
Did you create the sensor config? And did you restart HA

**Comment by Moossie72** [comment]
I don’t know how. Hacs did a lot automatically in the custom map. Do I have
to do something else?

Op wo 26 jan. 2022 om 21:54 schreef ymoona ***@***.***>

**Comment by pippyn** [comment]
Please look at the [example config](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#install). As you have installed the sensor through HACS, you don't need to copy the files again.

Look at the [HA documentation](https://www.home-assistant.io/docs/configuration/devices/) to add sensors in the YAML config.

**Comment by Moossie72** [comment]
Thanks for helping me.

Still I don't get it and get the following error:

*can not read a block mapping entry; a multiline key may not be an implicit
key at line 32, column 15:*

*          dateonly: 0                      (optional)*
*                  ^ *

I have copied the  example config
<https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#install>.
to /config/configuration.yaml
like below:

sensor:
    - platform: afvalbeheer
      wastecollector: MijnAfvalwijzer            (required)
      resources:                       (at least 1 required)
        - restafval
        - gft
        - papier
        - pmd
      postcode: xxxxxx                 (required)
      streetnumber: xx                  (required)
      suffix: a                        (optional)
      upcomingsensor: 0                (optional)
      dateformat: '%d-%m-%Y'           (optional)
      dateonly: 0                      (optional)
      dateobject: 0                    (optional)
      name: ''                         (optional)
      nameprefix: 1                    (optional)
      builtinicons: 0                  (optional)
      disableicons: 0                  (optional)
      dutch: 0                         (optional)

Op do 27 jan. 2022 om 08:19 schreef Pippyn ***@***.***>:

**Comment by pippyn** [comment]
Remove all the `(required)` and `(optional)` entries from your config. Like so:
```
sensor:
    - platform: afvalbeheer
      wastecollector: MijnAfvalwijzer 
      resources: 
        - restafval
        - gft
        - papier
        - pmd
      postcode: xxxxxx
      streetnumber: xx
      suffix: a 
      upcomingsensor: 0
      dateformat: '%d-%m-%Y'
      dateonly: 0
      dateobject: 0
      name: ''
      nameprefix: 1
      builtinicons: 0
      disableicons: 0
      dutch: 0
```
