### ISSUE TITLE
Papier "onbekend"

### ISSUE THREAD

**Issue by Toolhead** [pippyn/Home-Assistant-Sensor-Afvalbeheer#296]
Getting no date on "papier", other items are fine. In the "DeAfvalApp" there is a date for "papier"
Config:
```
  - platform: afvalbeheer
    wastecollector: DeAfvalApp
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: XXXX XX
    streetnumber: X
    upcomingsensor: 1
    dateonly: 1
    builtinicons: 0
    dutch: 1
```
