### ISSUE TITLE
Configuration yaml not working

### ISSUE THREAD

**Issue by misterwaldo** [pippyn/Home-Assistant-Sensor-Afvalbeheer#298]
Hi,

I am trying to install the sensor, but the given configuration isn't working. I tried different indentations with the below being the least vague outcome, stating the different properties aren't allowed and the "state" property missing.
![image](https://user-images.githubusercontent.com/1815071/152829420-0c99efc7-aa97-4a84-8c36-c8b3151d6d23.png)

**Comment by pippyn** [comment]
The property state is definitely not missing. This is VSCode reporting errors where there are none. 
Your config looks fine. what does your log say after a restart?

**Comment by misterwaldo** [comment]
`2022-02-07 17:51:50 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-07 17:54:28 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 11).
2022-02-07 17:54:28 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139622341136048] The system cannot restart because the configuration is not valid: Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 11). `

configuration.yaml line 11 refers to the sensor:
`sensor: !include afvalbeheer.yaml`

**Comment by misterwaldo** [comment]
It turns out it was my own configuration fault.
I included the sensor in the configuration, wanting to keep code separated :)
The inclusion was
`sensor: !include afvalbeheer.yaml`

and the yaml file itself was copied from the example. However, when including files the **sensor:** should not be declared again. This breaks it. So now I just set the same config without the sensor part:
```
- platform: afvalbeheer
  wastecollector: AfvalAlert
  resources:
    - restafval
    - gft
    - papier
    - pmd
    - textiel
  postcode: xxxxxx
  streetnumber: xx
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dateonly: 0
  dateobject: 0
  name: ""
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 0  
```

Although the VsCode plugin is still giving errors on the properties not being allowed, the configuration validation passes and I am able to restart the server and use the sensors.
