### ISSUE TITLE
getting only unkown results

### ISSUE THREAD

**Issue by alvi72** [pippyn/Home-Assistant-Sensor-Afvalbeheer#303]
I love this function and had it on my toon, but I seem to be unable to get it working on my HA and after scratching my head until they hairs started to fall out I thought i better ask here.

installed afvalbeheer via hacs.
Included the sensors information:
```
- platform: afvalbeheer
  wastecollector: Avalex
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: XXXXXX
  streetnumber: X
  upcomingsensor: 1
  builtinicons: 1 
```
all sensors return unkown optional today and tomorrow return none

potential issue when logging into the website it will ask for the address but ultimately always ask for a verfication of the address since there is als an identical adress with the suffix g, but that seems to be an unlikely cause I could define a suffix, so that issues seems to have been tackled.

Any idea where things are going wrong?

**Comment by pippyn** [comment]
Did you try and add the suffix to your config?
```
- platform: afvalbeheer
  wastecollector: Avalex
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: XXXXXX
  streetnumber: X
  suffix: "g"
  upcomingsensor: 1
  builtinicons: 1 
```
If that doesn't work; could you DM me your address on the HA forum? [This is me](https://community.home-assistant.io/u/pippyn)
