### ISSUE TITLE
"Special" Waste Collectors not working (RecycleApp)

### ISSUE THREAD

**Issue by yornola** [pippyn/Home-Assistant-Sensor-Afvalbeheer#305]
Gebruik makend via RecycleApp in Belgie.
Volgens de website van RecycleApp zijn volgende waste collectors ook aanwezig bij ons: 'Snoeihout', 'houtafval' en 'gemende metalen'.
Bij het toevoegen van snoeihout gaf hij een onbekende foutweergave. Al de rest geprobeerd maar blijkt ook niet te werken.

![afbeelding](https://user-images.githubusercontent.com/40866201/158584642-ba1955d3-05f7-46f7-9dcd-80a5c061d172.png)

**Comment by pippyn** [comment]
Use the option [`Print all available waste fractions`](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#print-all-available-waste-fractions) to see which fraction are supported by your collector.

**Comment by yornola** [comment]
As I thought only the standard ones are working (GFT, papier, PMD and restafval)

Is there a possibility to add the others for RecycleApp: (gemengde metalen, houtafval, kerstbomen en snoeihout)?
They're showing up in RecycleApp (except glass but that doesn't get picked up here).

**Comment by pippyn** [comment]
all available fractions are added automatically. You could DM me your address on the HA forum and I'll check that everything is working as it should be.

**Comment by yornola** [comment]
> all available fractions are added automatically. You could DM me your address on the HA forum and I'll check that everything is working as it should be.

I couldn't find you but the adress is Dendermonde 9200 in Belgium. As street you can choose " Grote Markt 1" (not real adress but same collector waste)

**Comment by pippyn** [comment]
The only available fractions in the API are:
```
Huisvuil (HV)
PMD
GFT
Snoeihout
Papier-karton
```
So this config will add all 5 sensors:
```
- platform: afvalbeheer
    wastecollector: recycleapp
    resources:
      - gft
      - papier
      - pmd
      - restafval
      - takken
    postcode: 9200
    streetnumber: 1
    streetname: "Grote Markt"
```
This was also correctly displayed by the printwastetypes option
