### ISSUE TITLE
GFT in Purmerend doesnt work anymore

### ISSUE THREAD

**Issue by Cl3tus** [pippyn/Home-Assistant-Sensor-Afvalbeheer#310]
Hello,

The option GFT does not work anymore in Purmerend. Sensor stays Unknown whilst Rest and Papier work fine. GFT used to work fine. Not sure if anything changed on the backend, i could not figure that out myself.

This is the YAML i'm using for a while which used to work fine.

```
- platform: afvalbeheer
  wastecollector: Purmerend
  resources:
    - restafval
    - gft
    - papier
  postcode: <masked>
  streetnumber: <masked>
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dateonly: 0
  name: "Afval"
  builtinicons: 0
  dutch: 1
```
![image](https://user-images.githubusercontent.com/35262361/162212911-dbd832e5-96e6-48e3-bf92-dbb9bd9ce789.png)

Anything i'm missing or do you need more info?

Thanks! Regards Paul
