### ISSUE TITLE
Gemeente leiden

### ISSUE THREAD

**Issue by ThomasKuijper** [pippyn/Home-Assistant-Sensor-Afvalbeheer#317]
I see that the gemeente leiden is missing from the implementation.
They do have an API, but they also use the 'mijnafvalwijzer' app, 
Tho the default mijnafvalwijzer integration doesn't give any values through the API:

https://api.MijnAfvalwijzer.nl/webservices/appsinput/?apikey=XXXXXX&method=postcodecheck&postcode=2317KJ&street=&huisnummer=2&toevoeging==&app_name=afvalwijzer&platform=phone&afvaldata=2022-06-15&langs=nl

I have found an 'api' call in the browser by looking at the network tab on: https://gemeente.leiden.nl/inwoners-en-ondernemers/afval/ophaalschema-afval/

So if needed i could make a pull request for a specific implementation for 'gemeente leiden', but i guess this would be less ideal. 
The better solution would be using mijnafvalwijzer.

Any ideas on how to resolve this?

**Comment by pippyn** [comment]
I've just looked into this, but the following config is working just fine for me:
```
  - platform: afvalbeheer
    wastecollector: mijnafvalwijzer
    resources:
      - gft
      - papier
      - restafval
    postcode: 2317KJ
    streetnumber: 2
```
Are there any errors in your log?
What is your config?
Is the custom component up-to-date?
