### ISSUE TITLE
RecycleApp results unknown - connection error

### ISSUE THREAD

**Issue by tom-lejeune** [pippyn/Home-Assistant-Sensor-Afvalbeheer#321]
Hi,
haven't changed anything in my setup but get error notification and results are "unknown"
```
  - platform: afvalbeheer
    wastecollector: RecycleApp 
    resources:                       
      - restafval
      - papier
      - pmd
      - glas
    postcode: 1700
    streetnumber: 17
    streetname: Libelstraat
    upcomingsensor: 1                
    dateformat: '%d-%m-%Y'           
    dateonly: 1
    dateobject: 0                   
    name: ''                        
    nameprefix: 1                  
    builtinicons: 0         
    disableicons: 0
    alwaysshowday: 1
    dutch: 1   
```

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1244
Integration: afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 14:34:39 (1 occurrences)
Last logged: 14:34:39

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa7b3bdf0>: Failed to establish a new connection: [Errno -3] Try again'))"))
