### ISSUE TITLE
add friendly names

### ISSUE THREAD

**Issue by CyborgNL** [pippyn/Home-Assistant-Sensor-Afvalbeheer#329]
Would it be possible to add friendly names to a type of waste? 
type: pmd
friendly_name: Plastic Metal en Drankkartons

The sensor today or tomorrow will show the friendly name iso pmd.
The reason asking is I like the use this for TTS. The same is for gft => Groente Fruit en Tuinafval.

<img width="377" alt="Schermafbeelding 2022-07-07 om 21 27 46" src="https://user-images.githubusercontent.com/61829624/177865735-d4e98759-b87d-4022-8e93-7e8293a485ed.png">

**Comment by RobHomey** [comment]
For now, I added 2 sensors in which I use the replace function. This works perfect with TTS for me.

{{ states('sensor.vandaag') | replace("pmd", "Plastic metalen en Drankkartons") | replace("gft", "Groente Fruit en Tuinafval") | replace("restafval", "Restafval") | replace("papier", "Papier") | replace("textiel", "Textiel")}}

{{ states('sensor.morgen') | replace("pmd", "Plastic metalen en Drankkartons") | replace("gft", "Groente Fruit en Tuinafval") | replace("restafval", "Restafval") | replace("papier", "Papier") | replace("textiel", "Textiel")}}

**Comment by FqfxLSNiKo** [comment]
Interested in this as well.

**Comment by pippyn** [comment]
You can change the name of every entity in HA.
https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by pippyn** [comment]
My bad. For now it's not possible to change the status name of the sensors.
I'll have a look if I can implement this.

**Comment by FqfxLSNiKo** [comment]
I'me quite new to HA and I thus prefer settings above YAML-files (also because it stops working after renaming the sensor's name). I've tried your solution, copied your lines litteraly, but it gives me an error. I've changed the name of the sensor, bit I guess I do something wrong. I'm not familiair with the right place for your line.

```
# Afvalkalender
afvalbeheer:
    wastecollector: PreZero
    resources:
        - restafval
        - gft
        - papier
        - pmd
    postcode: 1000AA
    streetnumber: 1
    #suffix: a                       # (optional)
    upcomingsensor: 1                # (optional)
    dateformat: '%d %B'           # (optional)
    dateonly: 0                      # (optional)
    name: "Afvalkalender"                         # (optional)
    nameprefix: 1                    # (optional)
    builtinicons: 0                  # (optional)
    dutch: 1                         # (optional)

    {{ states(sensor.prezero_afvalkalender_vandaag') | replace("pmd", "Plastic metalen en Drankkartons") | replace("gft", "Groente Fruit en Tuinafval") | replace("restafval", "Restafval") | replace("papier", "Papier") | replace("textiel", "Textiel")}}
```

Can you share your exact yaml-file (anominized)?
