### ISSUE TITLE
Add Attribute with date value (to enable sorting) 

### ISSUE THREAD

**Issue by kaosmagix** [pippyn/Home-Assistant-Sensor-Afvalbeheer#33]
Hi, I use this component for a long time. I want to be able to display the fraction collection sorted by date. [https://github.com/thomasloven/lovelace-auto-entities] provides the option for sorting by state (or attribute and others). However the date output of this component is of the type string. This means it will sort alphabetically on the date. This results in wrong sorting in my preferred date format '%d-%m-%Y'  For example 07-02-2020, 14-01-2020, 20-01-2020.
I can change the output dateformat of this component to get the sorting to work ('%Y-%m-%d') but I don't like that output (not to speak about my wife).

I think the best option to get this to work is to add a new attribute to the sensors with the actual date value (or the '%Y-%m-%d'value). That way we can sort the entities by Attribute, and can use any display state value without affecting the sort order.

**Comment by pippyn** [comment]
I get your point. I'm not sure if we are able to push the state as a date instead of a string. I'll need to check. Another option would be to implement an extra attribute with the date as an number (i.e. 20200131). Then the date in number format will always be higher for a new date. Will this work for your sorting needs?

**Comment by kaosmagix** [comment]
To avoid issues I would not change State as that works just fine for displaying the dates. Indeed implement it as an extra attribute. The attribute could be any of the following types: datetime (just like the lat updated attributes), numeric (in the yyyymmdd format) or string (in the yyyy-mm-dd format). I have seen my request more often in this issue list (to be able to sort the entity list by date) and this change + the use of the auto-entities component would provide this functionality.

Great!

**Comment by pippyn** [comment]
Added in release v2.5.9

**Comment by kaosmagix** [comment]
Great! It works:

Example:

configuration.yaml:

```
platform: afvalbeheer
wastecollector: GAD
resources:
  - gft
  - pbd
  - restafval
  - papier
postcode: 0000ZZ
streetnumber: 00
upcomingsensor: 1
dateformat: '%d-%m-%Y'
dateonly: 1
nameprefix: 1
builtinicons: 0
```

lovelace:
```
  - type: custom:auto-entities
    card:
      type: glance
      show_name: false
      columns: 4
    filter:
      include:
      - entity_id: sensor.gad_gft
      - entity_id: sensor.gad_pbd
      - entity_id: sensor.gad_restafval
      - entity_id: sensor.gad_papier
    sort:
      method: attribute
      attribute: "Sort-date"
      numeric: true
```
