### ISSUE TITLE
Feature request: calendar

### ISSUE THREAD

**Issue by tnagels** [pippyn/Home-Assistant-Sensor-Afvalbeheer#332]
It would be great if this integration could provide a calendar with the next pickup dates for all fractions. That way it can be shown on the central home assistant calendar.

Edit: I just noticed there is an open pull request for this. So consider this my vote for this feature being implemented!

**Comment by pippyn** [comment]
I agree, but for now it's still a wip.
Once it's fully tested I will release this update.

**Comment by pippyn** [comment]
v5.0.0 adds support for the calendar entity. Please note that you will have to change your config in order to use this new feature:
- Update the custom component
- Restart HA
- Remove the config of this component in the sensor platform
- Add this component as a platform in configuration.yaml ([example config](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#install))
- Restart HA

**Comment by thomas-svrts** [comment]
it would also be nice if you could create several calendars. Now in lovelace the monthly calander doesn't show the descriptions on small screens, different colors would be helpfull:

![image](https://user-images.githubusercontent.com/81048302/189830407-83734992-80e6-424f-a085-11558c936e5a.png)

I tried the config like below, but it still keeps only creating 1 calendar

```
afvalbeheer:
  - wastecollector: RecycleApp
    resources:
      - restafval
    postcode: xxxxxx
    streetnumber: xxxxxx
    streetname: xxxxxx
    upcomingsensor: 1
    builtinicons: 1
    name: restafval
  - wastecollector: RecycleApp
    resources:
      - papier
    postcode: xxxxxx
    streetnumber: xxxxxx
    streetname: xxxxxx
    upcomingsensor: 1
    builtinicons: 1
    name: papier
  - wastecollector: RecycleApp
    resources:
      - pmd
    postcode: xxxxxx
    streetnumber: xxxxxx
    streetname: xxxxxx
    upcomingsensor: 1
    builtinicons: 1
    name: pmd
```
