### ISSUE TITLE
Example config for 2 adresses

### ISSUE THREAD

**Issue by diedvdyk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#336]
Do you have an example config for 2 adresses in the new setup ?

**Comment by pippyn** [comment]
Sure!
```
afvalbeheer:
  - wastecollector: Blink
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1111AA
    streetnumber: 1
  - wastecollector: Blink
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1111AA
    streetnumber: 2
```
