### ISSUE TITLE
colored icons

### ISSUE THREAD

**Issue by petrolboerke** [pippyn/Home-Assistant-Sensor-Afvalbeheer#356]
Hello,

I can't get the collored icons to show.
When I go the status of the sensors, the will give me the correct icon-data. entity_picture is is using the collored data.
But home assistant keeps showing the old icons.

Also, when I set the icons to 0. These old icons keeps showing.

**Comment by pippyn** [comment]
what version of the sensor are you using?
what is your config of the sensor?
Any errors in your logs?

**Comment by petrolboerke** [comment]
No errors and I'm using the latest version. Like I said, the property 'entity_picture' is using the colored data.
Config is like this:
`afvalbeheer:
    wastecollector: RecycleApp
    printwastetypes: 1
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 2547
    streetnumber: 90
    streetname: "*********"
    upcomingsensor: 1
    dateformat: "%d %b"
    dayofweek: 1
    alwaysshowday: 1
    dateonly: 0
    dateobject: 0
    name: ""
    nameprefix: 1
    builtiniconsnew: 1
    dutch: 1
    updateinterval: 1`

**Comment by pippyn** [comment]
The option `builtinicons` has to be 1 also
```
afvalbeheer:
  - wastecollector: RecycleApp
    printwastetypes: 1
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 2547
    streetnumber: 90
    streetname: "*********"
    upcomingsensor: 1
    dateformat: "%d %b"
    dayofweek: 1
    alwaysshowday: 1
    dateonly: 0
    dateobject: 0
    name: ""
    nameprefix: 1
    builtinicons: 1
    builtiniconsnew: 1
    dutch: 1
    updateinterval: 1
```
