### ISSUE TITLE
limburg.net issue?

### ISSUE THREAD

**Issue by KurtKeunen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#362]
Cant seem to set up the limburg.net wastecollecter, i keep getting the error of not entering a city name while its in the config?

![image](https://user-images.githubusercontent.com/4628973/204909863-f940fe75-01d5-463c-9993-cf06ff089e44.png)
![image](https://user-images.githubusercontent.com/4628973/204910065-4f198a8a-52c4-4a8f-959e-5e3785719e91.png)

**Comment by pippyn** [comment]
You are using underscores where there should be none.
It is `streetnumber`, not `street_number`. The same with street_name and city_name.

PS In the future please share your config as text, not as a screenshot.

**Comment by KurtKeunen** [comment]
> You are using underscores where there should be none.
> It is `streetnumber`, not `street_number`. The same with street_name and city_name.
> 
> PS In the future please share your config as text, not as a screenshot.

even with no underscores it gives the samen result, really strange..

**Comment by pippyn** [comment]
Can you share your config please, so I better see what's wrong? 
You can just use a different address in your city.

**Comment by KurtKeunen** [comment]
There you go :) thx for looking
```
  afvalbeheer:
  wastecollector: Limburg.NET
  postcode: 3620
  streetnumber: 10
  streetname: "dorpstraat"
  cityname: "Lanaken"
  printwastetypes: 1
  upcomingsensor: 1 # (optional)
  dateformat: "%d-%m-%Y" # (optional)
  dateonly: 0 # (optional)
  name: "Afvalophaling" # (optional)
  nameprefix: 1 # (optional)
  builtiniconsnew: 1
  dutch: 1 # (optional)
  resources:
    - restafval
    - gft
    - papier
    - pmd
```
