### ISSUE TITLE
Value 'Unknown' day after pickup

### ISSUE THREAD

**Issue by goedh452** [pippyn/Home-Assistant-Sensor-Afvalbeheer#363]
A day after te pickup the value of a sensor is Unknown. This goes for all sensors. Is this something that is caused by the provider (PreZero) of maybe in the module?

This is my config:
`afvalbeheer:
  wastecollector: PreZero
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 0000AA
  streetnumber: 00
  dayofweekonly: 1
  dutch: 1`

<img width="389" alt="Scherm­afbeelding 2022-12-20 om 07 58 54" src="https://user-images.githubusercontent.com/20648665/208603231-2c8877ed-869f-4c18-a835-50b4261565e0.png">

**Comment by pippyn** [comment]
That is probably the collector. Do you have an address for me to test with?

**Comment by goedh452** [comment]
Thanks for the quick reply! This is the address of the railway station in the samen area: 6811 MA, 166.

**Comment by pippyn** [comment]
I'll look into this issue further

**Comment by pippyn** [comment]
Do you mean RD4? Yes the API uses the year in the request. 
But we are talking about PreZero here, which is using the Opzet API and doesn't us the year in the request.
It could be that PreZero has not yet released the calendar for next year though.

**Comment by ymatsiuk** [comment]
Yeah, sorry, I was talking about RD4. Shall I open a separate issue for the API's that have year in the request?

**Comment by goedh452** [comment]
This is the card now. Somehow the state is unknown the next day after te pickup and during the day it correct state is retrieved. 
![Uploading 87DAC162-8DBD-499B-96B0-16B9E06540D9.jpeg…]()

**Comment by mkoorn** [comment]
Hi @pippyn, I am having the same issue, started after new years.

The provider is HVC, test address is 1648JG, 2 (city hall)

The state is indeed corrected during the day, but the trouble is that I have notifications set up at 8:00 AM.
On the day after, I also get this notification.

I have a conditions set for the notification
`{{ state_attr('sensor.hvc_papier', 'Days_until') == 0 }}`

Any idea's on how to fix or how I can improve so that I don't get the notification multiple times?

Thanks for your work!

my config is:
```
sensor:
    - platform: afvalbeheer
      wastecollector: HVC
      resources:
        - restafval
        - gft
        - papier
        - pmd
      postcode: "1648JG"
      streetnumber: 2
      upcomingsensor: 1
      dateformat: '%d %b'
      dateonly: 0
      nameprefix: 1
      builtinicons: 0
      dutch: 1
      printwastetypes: 0
      dayofweek: 0
      dayofweekonly: 1
```
