### ISSUE TITLE
Value "Onbekend" in the entities

### ISSUE THREAD

**Issue by niterfjord** [pippyn/Home-Assistant-Sensor-Afvalbeheer#365]
Hello

With the code below, I get the following entities but without dates.

```
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
  postcode: 1570
  streetnumber: 5
  streetname: Brusselstraat
```

![image](https://user-images.githubusercontent.com/66115112/209028809-eb22537b-1fbb-4cdb-bfc6-f9f1c7953be0.png)

Does anyone know what is going wrong?

**Comment by iSenne85** [comment]
I have the same issue

```
sensor:
  - platform: rflink
    automatic_add: false
  - platform: afvalbeheer
    scan_interval: 300
    wastecollector: ACV
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 3904ZZ
    streetnumber: 3
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    nameprefix: 0
```
![Screenshot 2022-12-22 at 08 14 42](https://user-images.githubusercontent.com/24296276/209078350-5f34b3f5-e5b3-4ddd-824d-5d743564ae81.png)

I don't think you are doing anything wrong, I thing there is a problem with the data.

**Comment by niterfjord** [comment]
> updateinterval



> I have the same issue
> 
> ```
> sensor:
>   - platform: afvalbeheer
>     scan_interval: 300
>     wastecollector: ACV
>     resources:
>       - restafval
>       - gft
>       - papier
>       - pmd
>     postcode: ####**
>     streetnumber: #
>     upcomingsensor: 1
>     dateformat: "%d-%m-%Y"
>     nameprefix: 0
> ```
> 
> ![Screenshot 2022-12-22 at 08 14 42](https://user-images.githubusercontent.com/24296276/209078350-5f34b3f5-e5b3-4ddd-824d-5d743564ae81.png)
> 
> I don't think you are doing anything wrong, I thing there is a problem with the data.
> 
> **Update 1:** I'm seeing error's in the log
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
>     await asyncio.gather(*pending)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in async_add_entities
>     self._async_unsub_polling = async_track_time_interval(
>   File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1380, in async_track_time_interval
>     remove = async_track_point_in_utc_time(hass, interval_listener_job, next_interval())
>   File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1366, in next_interval
>     return dt_util.utcnow() + interval
> TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'
> ```
> 
> **Update 2:** Scratch this. In my case I didn't read the changelog while updating 🤦 . Changed the `scan_interval` to `updateinterval` and it's working again 😄

Where or in what file did you put that code?

**Comment by pippyn** [comment]
What @iSenne85 mentioned has nothing to do with your issue. 

I tested your config and it is working fine for me. Do you have any errors in your log?

**Comment by niterfjord** [comment]
I tested with @iSenne85 his code and then it does work, only I get no buildinnewicons while I set that to 1.
Where exactly can I find the afvalbeheer logs?

**Comment by pippyn** [comment]
That code has only effect on the update interval. So it shouldn't fix your issue.

What is your config now?

Logs can be found here Settings > System > Logs

**Comment by niterfjord** [comment]
Config:
```
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
  postcode: 1570
  streetnumber: 5
  streetname: Brusselstraat
  upcomingsensor: 1
  dateonly: 1
  builtiniconsnew: 1
  dutch: 1
```

Logs:
```
Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1a29fce80>: Failed to establish a new connection: [Errno -3] Try again'))"))
```

**Comment by pippyn** [comment]
I think the API is rate limiting you. Wait 1 or 2 days and this error should be gone.

Add the option `builtinicons: 1` and the icons should work:
```
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
  postcode: 1570
  streetnumber: 5
  streetname: Brusselstraat
  upcomingsensor: 1
  dateonly: 1
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 1
```

**Comment by niterfjord** [comment]
Now it does work. But with which option can I ensure that there are designations such as today, tomorrow, ...
![image](https://user-images.githubusercontent.com/66115112/209145521-f7b20828-3626-47e5-8069-0cdf0d6db567.png)

**Comment by pippyn** [comment]
With [this option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#always-show-day) 

`alwaysshowday: 1`

**Comment by D3xtar** [comment]
Unfortunately I am experiencing the same issue. Our waste collector is Omrin.

In the log i see:

```
Logger: homeassistant
Source: custom_components/afvalbeheer/API.py:597
Integration: Afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 12:01:35 (1 occurrences)
Last logged: 12:01:35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/API.py", line 133, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/API.py", line 597, in update
    for item in response:
TypeError: 'NoneType' object is not iterable
```

My config:

```
Afvalbeheer:
  wastecollector: Omrin
  resources:
    - restafval
    - gft
    - papier
  postcode: 9101AA
  upcomingsensor: 0                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 0                  # (optional)
  dutch: 0                         # (optional)
```
