### ISSUE TITLE
recycleapp_tomorrow.state report duplicated items

### ISSUE THREAD

**Issue by hilsonp** [pippyn/Home-Assistant-Sensor-Afvalbeheer#367]
Hello,

Today, I saw that the sensor.recycleapp_tomorrow reported duplicated items in its state.
Eg:
![image](https://user-images.githubusercontent.com/7338241/210183284-06eab5dd-89e1-4ae2-b397-4b1d22f94b2a.png)

My configuration is:
```
sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - gft
      - papier
      - pmd
      - textiel
    postcode: !secret postcode
    streetname: !secret streetname
    streetnumber: !secret streetnumber
    #suffix: a
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    dateonly: 0
    dateobject: 0
    alwaysshowday: 1
    name: ""
    nameprefix: 1
    builtinicons: 1
    disableicons: 1
    dutch: 0
```

I'm not sure when this happened the first time. I only saw this today.

Best regards and thanks a lot. This integration is really helpful !

Pierre
