### ISSUE TITLE
Calendar does not seem to trigger automations

### ISSUE THREAD

**Issue by teranex** [pippyn/Home-Assistant-Sensor-Afvalbeheer#369]
Thank you for this integration. I'm using it for the RecycleApp wastecollector.

I'm also trying to setup a Calendar automation to automatically get a notification the day before a collection so we don't forget to put out the trash. So far I did not succeed in setting this up.
In the HA core I found one issue mentioning a similar problem for another integration (https://github.com/home-assistant/core/issues/74229) but it doesn't mention what the exact problem was with that integration.

This is from my configuration.yaml:

```yaml
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: xxxxx
  streetname: xxxx
  upcomingsensor: 0 # (optional)
  dateformat: "%d/%m/%Y" # (optional)
  dateonly: 0 # (optional)
  name: "" # (optional)
  nameprefix: 1 # (optional)
  builtinicons: 1 # (optional)
  builtiniconsnew: 1
  dutch: 1 # (optional)
```
This is my automation:
```yaml
- id: "1672318605220"
  alias: Melding afvalophaling
  description: ""
  trigger:
    - platform: calendar
      event: start
      offset: "-5:0:0"
      entity_id: calendar.afvalbeheer_recycleapp
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.schouw_melding_bruin
      metadata: {}
    - service: lametric.message
      data:
        device_id: xxx
        message: Afval buiten zetten
        sound: alarm2
        cycles: 0
        icon_type: alert
        priority: critical
    - service: notify.telegram_gezin_notifier
      data:
        message: Afval test melding
  mode: single
```
