### ISSUE TITLE
resource: Keukenafval / GFT Buitengebied toevoegen 

### ISSUE THREAD

**Issue by Brandweerman** [pippyn/Home-Assistant-Sensor-Afvalbeheer#374]
After a lot of research I found that for "mijnafvalwijzer" the "GFT buitengebied" waste is visibly displayed when the resource "keukenafval" is added.

{"nameType":"gft buitengebied","type":"keukenafval","date":"2023-01-04"}

Is it possible to add this resource (to the manual) and also link the GFT logo to it?

**************************************************************
Na flink wat uitzoekwerk gevonden dat voor "mijnafvalwijzer" het "GFT buitengebied" afval zichtbaar wordt weergegeven als de recource "keukenafval" wordt toegevoegd. 

{"nameType":"gft buitengebied","type":"keukenafval","date":"2023-01-04"}

Is het mogelijk om deze resource toe te voegen (aan de handleiding) en ook het GFT logo hier aan te koppelen?

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by Brandweerman** [comment]
Bolst 13, 5469 SC Erp

**Comment by pippyn** [comment]
This config is working fine for me:
```
afvalbeheer:
  - wastecollector: MijnAfvalwijzer
    resources:
      - restafval
      - keukenafval
      - pmd
      - papier
    postcode: 5469SC
    streetnumber: 13
```
