### ISSUE TITLE
Is it possible to add iCal integration

### ISSUE THREAD

**Issue by SvenNL74** [pippyn/Home-Assistant-Sensor-Afvalbeheer#379]
Hi,

the place I live gives you the option to download a PDF or an iCal, the last one is readable and should be easily harvestable (assumption on my part)? Is it possible to add that? 

Example:
https://www.gemeentelandvancuijk.nl/afvalkalender/

you can use: 5835 AT, number 1 (address of a cafe)

This brings you to:
https://www.gemeentelandvancuijk.nl/afvalkalender/5835AT/1

It could be that they use a api to get this data, I do not know.

Thanks in advance!

**Comment by pippyn** [comment]
Hi @SvenNL74,

No this sensor will not support iCal, but your municipality also supports DeAfvalApp!
So you could use that integration for your waste collections:
```
afvalbeheer:
  - wastecollector: DeAfvalApp
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 5835AT
    streetnumber: 1
```
