### ISSUE TITLE
Inegration with ROVA not working

### ISSUE THREAD

**Issue by Johan219** [pippyn/Home-Assistant-Sensor-Afvalbeheer#383]
Hello, I've been trying to integrate ROVA into "afvalbeheer" for a few evenings now, but I can't get it to work. 

I think I did everything according to instructions, but I see the following in sensors at entities:

![ROVA](https://user-images.githubusercontent.com/59110584/222687133-ddd24467-7106-47d9-9894-86a934f99639.jpg)

I get the following error message in the log:

> Traceback (most recent call last):
>   File "/config/custom_components/afvalbeheer/API.py", line 132, in async_update
>     await self.collector.update()
>   File "/config/custom_components/afvalbeheer/API.py", line 273, in update
>     data = (response['ophaaldagen']['data'] + response['ophaaldagenNext']['data'])
> KeyError: 'ophaaldagen'

Below is my configuration. In the ROVA app, I get to see all the data.  What am I doing wrong?
```
afvalbeheer:
  wastecollector: ROVA
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 8131NS
  streetnumber: #secret
  suffix: a                        
  upcomingsensor: 1                
  dateformat: '%d-%m-%Y'           
  dateonly: 0                      
  name: ""                         
  nameprefix: 1                    
  builtinicons: 0                  
  dutch: 1     
```
