### ISSUE TITLE
Avalex not showing PMD

### ISSUE THREAD

**Issue by leadenchopsticks** [pippyn/Home-Assistant-Sensor-Afvalbeheer#394]
PMD always states "unknown" at my dashboard.  I enabled `printwastetypes` and Afvalbeheer says "Available waste types: gft, papier, restafval" for Avalex. So it seems PMD is missing. Can you enable this or is this an error at Ximmio?

**Comment by pippyn** [comment]
Does the Avalex website give you the correct data?
Do you have an address for me to test with?

**Comment by pippyn** [comment]
This config with the address you provided is working fine:
```
afvalbeheer:
  - wastecollector: Avalex
    resources:
      - gft
      - pmd
      - papier
    postcode: 2286JZ
    streetnumber: 1
    printwastetypes: 1
```
![image](https://user-images.githubusercontent.com/7591990/232447484-1be32e42-06f2-4600-baa2-ba57515c6d32.png)
