### ISSUE TITLE
Almere no restafval

### ISSUE THREAD

**Issue by E020** [pippyn/Home-Assistant-Sensor-Afvalbeheer#395]
Almere goes from duo to mono, so the duocontainers are replaced to one resafvall and one GFT.
I only added restafval to the config, but the restafval info is not in the FE displayed all other info is correct. Almere site offers the update info. No idea why this isn't working.

```
- platform: afvalbeheer
  wastecollector: almere
  resources:
    - restafval
    - gft
    - pmd
    - papier
  postcode: !secret afval_postcode
  streetnumber: !secret afval_streetnumber
  upcomingsensor: 1
  dateformat: '%d %b'
  alwaysshowday: 1
  dayofweek: 1
  dateonly: 0
  dateobject: 0
  name: ''
  nameprefix: 1
  builtinicons: 1
  disableicons: 0
  dutch: 1 
```
