### ISSUE TITLE
Restafval Omrin

### ISSUE THREAD

**Issue by daniels1989** [pippyn/Home-Assistant-Sensor-Afvalbeheer#396]
Hey Pippyn,

I can't seem to get restafval to work with Omrin, but it's quite possible that I'm just doing something wrong.

config: 
```yaml
afvalbeheer:
  - wastecollector: Omrin
    resources:
      - restafval
      - gft
    postcode: 9561AA
    streetnumber: 1
    printwastetypes: 1
```

The notification prints out "Available waste types: chemisch, elektrische apparaten, gft, grofvuil, restafval container, snoeiafval"

Apart from gft, I don't see the others being mapped in the OmrinCollector in API.py.

**Comment by pippyn** [comment]
Hi @daniels1989,

Only some fractions need to be mapped in order to circumvent connflicts.

This config is working fine for me:
```
afvalbeheer:
  - wastecollector: Omrin
    resources:
      - chemisch
      - elektrische apparaten
      - gft
      - grofvuil
      - restafval container
      - snoeiafval
    postcode: 9561AA
    streetnumber: 1
    printwastetypes: 1
```
