### ISSUE TITLE
DeAfvalApp no longer working? 

### ISSUE THREAD

**Issue by NoahvdVen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#406]
DeAfvalApp worked perfectly with this integration, until a few days ago. The "days-untill" sensor keeps giving back the state "null". Any ideas on how to fix this? 

![DeAfvalApp issue](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/98456913/e2b335b1-c649-4f93-aa4f-f5fb8cf9b676)

**Comment by NoahvdVen** [comment]
5709MG, 9

The app gives me the correct dates. 

I have already tried reinstalling the integration, reload the config etc.

**Comment by pippyn** [comment]
This config is working fine for me:
```
afvalbeheer:
  - wastecollector: DeAfvalApp
    resources:
      - gft
      - kerstbomen
      - papier
      - pmd
      - restafval
    postcode: 5709MG
    streetnumber: 9
    printwastetypes: 1
```

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/7591990/dbc93937-5c74-4a12-aba6-7cc5b597c8b6)

Do you have any errors in your log?
