### ISSUE TITLE
Afval3xbeter

### ISSUE THREAD

**Issue by jeroen84s** [pippyn/Home-Assistant-Sensor-Afvalbeheer#407]
Can you add Afval3xbeter for this intergration? (Etten-Leur)

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by jeroen84s** [comment]
4876VK and and you can choose your own house number

**Comment by pippyn** [comment]
Added in v5.2.7

Sample config:
```
afvalbeheer:
  - wastecollector: Afval3xBeter
    resources:
      - gft
      - papier
      - restafval
    postcode: 4876VK
    streetnumber: 1
    printwastetypes: 1
```
