### ISSUE TITLE
Omrin only showing GFT

### ISSUE THREAD

**Issue by gertjanlok** [pippyn/Home-Assistant-Sensor-Afvalbeheer#413]
When setting up for Omrin **_GFT_** is showing fine.
_**Restafval**_ however is always on "Onbekend".

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/148001068/23ff034f-25bf-49a5-b8d3-edfa4155dea9)

**Comment by gertjanlok** [comment]
Address to test: 9561 AG, 126

**Comment by pippyn** [comment]
This config is working fine for me:
```
afvalbeheer:
  - wastecollector: Omrin
    resources:
      - chemisch
      - elektrische apparaten
      - gft
      - grofvuil
      - restafval container
      - snoeiafval
    postcode: 9561AG
    streetnumber: 126
```
![Screenshot 2023-10-16 at 08 29 23](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/7591990/0e4b0035-1104-443e-9158-5c4b95225b14)
