### ISSUE TITLE
Bar afvalbeheer showing "onbekend" for PMD / rest

### ISSUE THREAD

**Issue by svdh-github** [pippyn/Home-Assistant-Sensor-Afvalbeheer#414]
Hi, trying to get paper gft and rest visible on the dashboard. GFT and paper work fine. The issue is with the rest afval. It keeps showing onbekend for the next pick-up date. ( see screenshot ). 

postcode: 3162XR nr.  16 

![afval](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/65946963/dd1e78ea-a999-4362-b026-be42a1f03e19)

Thanks in advance

**Comment by pippyn** [comment]
This config is working fine:
```
afvalbeheer:
  - wastecollector: Bar
    resources:
      - gft
      - papier
      - pmd-restafval
    postcode: 3162XR
    streetnumber: 16
    printwastetypes: 1
```
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/7591990/780c9acb-d54c-4daa-bb43-675196260010)
