### ISSUE TITLE
Spaarnelanden not showing duobak

### ISSUE THREAD

**Issue by Fraggz** [pippyn/Home-Assistant-Sensor-Afvalbeheer#415]
Hi,

In response to my request regarding the ticket for my issue:

Spaarnelanden is not displaying the duobak in my calendar, and there's no information available on the sensor. However, the dates for restafval and GFT are being shown.

I attempted to add a few more names that I thought would work, but unfortunately, no data is being displayed. I also included the 'printwastetypes', but I can't seem to locate the log where the names are displayed. I'm new to HA, so my apologies for any confusion!

Additionally, would it be possible for me to add the "schoonmaakweken" that I found on https://afvalwijzer.spaarnelanden.nl/afvalkalender?

  afvalbeheer:
      wastecollector: Spaarnelanden
      resources:
        - restafval
        - gft
        - papier
        - pmd
        - duobak
        - pbd
      postcode: 2041CJ
      streetnumber: 80
      upcomingsensor: 1                # (optional)
      dateformat: '%d-%m-%Y'           # (optional)
      dateonly: 0                      # (optional)
      name: ""                         # (optional)
      printwastetypes: 1
      nameprefix: 1                    # (optional)
      builtinicons: 1                  # (optional)
      builtinicons: 1
      dutch: 1                         # (optional)

**Comment by pippyn** [comment]
This config is working fine for me:
```
afvalbeheer:
  - wastecollector: Spaarnelanden
    resources:
      - gft
      - papier-pmd
      - restafval
    postcode: 2041CJ
    streetnumber: 80
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    dateonly: 0
    name: ""
    printwastetypes: 1
    nameprefix: 1
    builtinicons: 1
    dutch: 1
```
You can view the result of `printwastetypes` under Notifications in the left bottom:
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/7591990/9ff61479-d02f-4544-9cd7-5094d9768e56)

I'll have a look at supporting `schoonmaakweken`
