### ISSUE TITLE
Alphen aan den Rijn not working

### ISSUE THREAD

**Issue by RickM1234** [pippyn/Home-Assistant-Sensor-Afvalbeheer#416]
I'm using the Afvalbeheer for the Alphen aan den Rijn region. Unfortunatly it doesn't work.
When I check mijnafvalwijzer.nl the website can't show the adress.
Do you know if there are any problems with that? I've removed my number in the code below.

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/149004232/27195a74-40c9-435b-a31f-d5a774f63066)

afvalbeheer:
  wastecollector: AlphenAanDenRijn
  resources:
    - papier
    - pmd
    - gft
  postcode: 2401
  streetnumber: 
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dateonly: 0
  dayofweek: 0
  dateobject: 1
  name: ""
  nameprefix: 0
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 1

**Comment by pippyn** [comment]
Hi @RickM1234,

What do you mean? Alphen aan den Rijn doesn't use the mijnafvalwijzer.nl service?
The following config works just fine:
```
afvalbeheer:
  - wastecollector: alphenaandenrijn
    resources:
      - papier
      - pmd
      - gft
    postcode: 2401AA
    streetnumber: 1
    upcomingsensor: 1
```
