### ISSUE TITLE
RecycleApp not giving any information

### ISSUE THREAD

**Issue by Vampyrebe** [pippyn/Home-Assistant-Sensor-Afvalbeheer#421]
Hello there, 

First and foremost, thank you very much for taking the time to create this plug in. I'm very happy it exists. 

Sadly for the moment for me, it's not working. For all the sensors I get an unknown result. It's most probably me doing something silly, I'm pretty new with home automations so... 

Here is my config in configuration.yaml
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 1785
  streetnumber: xx (it's a number between 1 and 40)
  streetname: Onze-Lieve-Vrouwstraat
  cityname: Merchtem
  upcomingsensor: 1                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: 'Poubelles'                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 1                  # (optional)
  builtiniconsnew: 1
  dutch: 0                         # (optional)

I've checked the other threads to make sure I wasn't missing anything. So I already tried to go on the recycleapp.be, and my adress works properly there. I also checked the HACS status and the instance has been properly restarted. I also get the different sensors in the dashboard, they just stay with Unknown status, or not available.
I'm not sure at all about what I'm doing wrong and would certainly appreciate the help. 

Thank you very much for your patience,

**Comment by pippyn** [comment]
Hi @Vampyrebe!

Why did you use dashes in the street name?
This config is working fine for me:
```
afvalbeheer:
  - wastecollector: RecycleApp
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1785
    streetnumber: 1
    streetname: Onze Lieve Vrouwstraat
    cityname: Merchtem
    upcomingsensor: 1 # (optional)
    dateformat: "%d-%m-%Y" # (optional)
    dateonly: 0 # (optional)
    name: "Poubelles" # (optional)
    nameprefix: 1 # (optional)
    builtinicons: 1 # (optional)
    builtiniconsnew: 1
    dutch: 0 # (optional)
```
