### ISSUE TITLE
Circulus collector not working

### ISSUE THREAD

**Issue by KvE-dev** [pippyn/Home-Assistant-Sensor-Afvalbeheer#424]
# Problem statement
The problem that I ran into seems to be only for the Circulus collector.
I have tried several ways of configuring this collector but still the data does not seem to get loaded from the Circulus source.

I have added somewhat the same config for Twente Milieu and this seems to work fine.

Everything seems fine accept the loading of the data:
- Icons work fine
- Calender is made
- Sensors are avalible

![Screenshot 2023-12-01 192040](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/26262784/3124f38e-726e-48b2-a26e-8438e89b3764)

One small sidenode: I am fairly new to Home assistant.

# Setup
- Afvalbeheer is installed via HACS
- Sensors are created correctly
- HA Core: 2023.11.3
- HA Supervisor: 2023.11.6
- HA Operating System: 11.1
- HA Frontend: 20231030.2
- HACS Integration version: 1.33.0
- HACS Frontend version:  20220906112053
- HA runs in a VM on my server

# Config
NOTE: Instead of secrets I have also tried putting in the adress.
```
afvalbeheer:
  - wastecollector: Circulus
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: !secret afvalbeheer_postcode_circulus
    streetnumber: !secret afvalbeheer_huisnummer_circulus
    # suffix: ""
    # upcomingsensor: 1
    # dateformat: "%d-%m-%Y"
    # dayofweek: 1
    # dayofweekonly: 1
    # dateonly: 0
    # name: ""
    nameprefix: 1
    builtinicons: 1
    builtiniconsnew: 1
    # dutch: 0
    # updateinterval: 12

  - wastecollector: TwenteMilieu
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: !secret afvalbeheer_postcode_twente
    streetnumber: !secret afvalbeheer_huisnummer_twente
    # suffix: a
    # upcomingsensor: 0
    # dateformat: '%d-%m-%Y'
    # dayofweek: 1
    # dayofweekonly: 1
    # dateonly: 0
    # name: ""
    nameprefix: 1
    builtinicons: 1
    builtiniconsnew: 1
    # dutch: 0
    # updateinterval: 12

```
