### ISSUE TITLE
Base entity names on configuration option 'dutch:'

### ISSUE THREAD

**Issue by Getslow6** [pippyn/Home-Assistant-Sensor-Afvalbeheer#426]
Hello!

First of all, thank you for developing this integration. 

I'm from the Netherlands, but use the integration in the English language with the following config:

```
afvalbeheer:
  wastecollector: HVC
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: [redacted]
  streetnumber: [redacted]
  upcomingsensor: 1
  alwaysshowday: 1
```

Note that the `dutch` option is not used:
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#translation

Since the last update, my entities have been renamed from:

`sensor.hvc_today` -> `sensor.hvc_vandaag`
`sensor.hvc_tomorrow` -> `sensor.hvc_morgen`

Would it be possible to tie the naming of the entities to the option `dutch`?
