### ISSUE TITLE
Gemeente Assen changed provider

### ISSUE THREAD

**Issue by MWolthuis** [pippyn/Home-Assistant-Sensor-Afvalbeheer#431]
Hello,
Is it possible to make changes so gemeente Assen can be used next year?

They moved from Afvalwijzer to Burgerportaal (21QUBZ) from the company 21South.

It is the same company that's being used bij BAR and RMN. A lot of info was already made available here:
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/382

Thank you.

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by MWolthuis** [comment]
Offcourse, 9407HM, number 77. Please let me know if you need more info.

**Comment by pippyn** [comment]
Added support in v5.2.12
Example config:
```
afvalbeheer:
  - wastecollector: Assen
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 9407HM
    streetnumber: 77
    printwastetypes: 1
    upcomingsensor: 1
```
