### ISSUE TITLE
Cleanprofs support

### ISSUE THREAD

**Issue by koenza** [pippyn/Home-Assistant-Sensor-Afvalbeheer#436]
Would be great if you could add Cleanprofs support. It is an additional service that cleans your trash cans 12 times per year after the garbage truck has passed. Handy to know you should not retreive them from the street immediatly on that particular day. 

https://www.cleanprofs.nl/reinigingsschema-ophaaldagen-v0/

**Comment by pippyn** [comment]
I'll look into it, but currently this sensor has no support for this additional info.
Do you have an address for me to test with?

**Comment by koenza** [comment]
You can access it with 5673BH housenumber 33. This address (not mine) has a subscription for both GFT and Rest.

**Comment by milamaja** [comment]
De JSON kan via een GET worden opgehaald:
`https://cleanprofs.jmsdev.nl/api/get-plannings-address?zipcode=[POSTCODE]&house_number=[HUISNUMMER]&start_date=2024-08-27&end_date=2024-11-30&code=crm`

De data die je krijgt ziet er vervolgens als volgt uit: (ingekort)

```
[
  {
    "product_name": "GFT",
    "weekday": "dinsdag",
    "date": "27 aug.",
    "full_date": "2024-08-27"
  },
  {
    "product_name": "RST",
    "weekday": "donderdag",
    "date": "29 aug.",
    "full_date": "2024-08-29"
  }
]
```

**Comment by pippyn** [comment]
Could you please test v5.3.8 of this sensor?
You can add your Cleanprofs configuration just as an extra waste collector

**Comment by milamaja** [comment]
> Could you please test v5.3.8 of this sensor? You can add your Cleanprofs configuration just as an extra waste collector

Works perfectly in 5.3.9

To be able to see the difference in the calendar. I experimented a little.
I first tried different waste types. But ended up with changing the calendar.py

From row 70, the append function. Is:
```
 events.append(
                        CalendarEvent(
                            summary=waste_items.waste_type,
                            start=waste_items.date.date(),
                            end=waste_items.date.date() + timedelta(days=1),
                        )
                    )
```

I changed that to:
```
                  if self.WasteData.waste_collector == "cleanprofs":
                        calmessage = "Schoonmaken " + waste_items.waste_type + " container"
                    else:
                        calmessage = waste_items.waste_type
                    
                    events.append(
                        CalendarEvent(
                            summary=calmessage,
                            start=waste_items.date.date(),
                            end=waste_items.date.date() + timedelta(days=1),
                        )
                    )
```

**Comment by paulvt** [comment]
I have tested v5.3.9 and the sensors for Cleanprofs work for me! Thanks!

**Comment by Pleister023** [comment]
uhm....quick question, how would the config look like with two wastecollectors? I have this now, and it only shows the CleanProfs schedule, not the Meerlanden one:

afvalbeheer:
  wastecollector: Meerlanden
  resources:
    - Restafval
    - PMD
  postcode: [mypostalcode]
  streetnumber: [myhousenumber]
  wastecollector: Cleanprofs
  resources:
    - GFT
  postcode: [mypostalcode]
  streetnumber: [myhousenumber]

**Comment by pippyn** [comment]
Like this:

```
afvalbeheer:
  - wastecollector: Meerlanden
    resources:
      - Restafval
      - PMD
    postcode: [mypostalcode]
    streetnumber: [myhousenumber]
  - wastecollector: Cleanprofs
    resources:
      - GFT
    postcode: [mypostalcode]
    streetnumber: [myhousenumber]
```

**Comment by flapskekort** [comment]
How would the config look like for the optional functions, added wit e "-" in front of it or for each wastecollector the appropriated functions?

suffix: a                        # (optional)
  upcomingsensor: 0                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 0                  # (optional)
  dutch: 0                         # (optional)

**Comment by pippyn** [comment]
What do you mean?
This?;

```
afvalbeheer:
  - wastecollector: Meerlanden
    resources:
      - Restafval
      - PMD
    postcode: [mypostalcode]
    streetnumber: [myhousenumber]
    suffix: a # (optional)
    upcomingsensor: 0 # (optional)
    dateformat: '%d-%m-%Y' # (optional)
    dateonly: 0 # (optional)
    name: "" # (optional)
    nameprefix: 1 # (optional)
    builtinicons: 0 # (optional)
    dutch: 0 # (optional)
  - wastecollector: Cleanprofs
    resources:
      - GFT
    postcode: [mypostalcode]
    streetnumber: [myhousenumber]
    suffix: a # (optional)
    upcomingsensor: 0 # (optional)
    dateformat: '%d-%m-%Y' # (optional)
    dateonly: 0 # (optional)
    name: "" # (optional)
    nameprefix: 1 # (optional)
    builtinicons: 0 # (optional)
    dutch: 0 # (optional)
```
