### ISSUE TITLE
Possible to Add RWM?

### ISSUE THREAD

**Issue by Mister9991** [pippyn/Home-Assistant-Sensor-Afvalbeheer#437]
Hello,

Is it possible to add also RWM to Afvalbeheer?
https://www.rwm.nl/

Thanks!

**Comment by dirixmjm** [comment]
@Mister9991  I added RWM.
If you are interested in testing it out, add this one:
https://github.com/dirixmjm/Home-Assistant-Sensor-Afvalbeheer

My config looks like:
```
afvalbeheer:
  wastecollector: RWM
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 6191KG
  streetnumber: 4
    #suffix:                         # (optional)
  upcomingsensor: 0                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  builtinicons: 1                  # (optional)
  builtiniconsnew: 1                  # (optional)
  dutch: 1                         # (optional)

```
