### ISSUE TITLE
Toevoegen gemeente Montferland

### ISSUE THREAD

**Issue by martreumer** [pippyn/Home-Assistant-Sensor-Afvalbeheer#446]
Is het mogelijk om de [gemeente Montferland](https://montferland.afvalwijzer.net/) toe te voegen?

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by martreumer** [comment]
7041CE with number 15

**Comment by pippyn** [comment]
This is a new API, so this version could contain some bugs. Could you test integration version v5.2.15?
Minimal config is:
```
afvalbeheer:
  - wastecollector: Montferland
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 7041CE
    streetnumber: 15
```
