### ISSUE TITLE
Can't add waste type

### ISSUE THREAD

**Issue by HayoV** [pippyn/Home-Assistant-Sensor-Afvalbeheer#449]
I'm new here and not sure how to post my chalange.

In my HA Afvalwijzer is configured for Spaarnelanden(Haarlem).
It works for sensors GFT, Today and Tomorow.

In notification I have:
Afvalwijzer spaarnelanden
Available waste types: de recyclewagen, gft, papier-pmd

When adding papier_pmd I get an error; Invalid entity ID at position 0:
sensor.spaarnelanden_papier-pmd

configuration.yaml:
```
afvalbeheer:
  wastecollector: Spaarnelanden
  resources:
    - gft
    - papier-pmd
  postcode: XXXXXX
  streetnumber: XXX
  upcomingsensor: 1
  printwastetypes: 1
  dateformat: '%d-%m'
  dateonly: 0
  dayofweek: 1
  dateobject: 0
  name: ''
  nameprefix: 1
  builtinicons: 1
  dutch: 1
```
Lovelace:
```
- type: entities
          entities:
            - entity: sensor.spaarnelanden_papier-pmd
            - entity: sensor.spaarnelanden_gft
            - entity: sensor.spaarnelanden_vandaag
            - entity: sensor.spaarnelanden_morgen
          title: Spaarnelanden
```
Any suggestions?
