### ISSUE TITLE
Possible to add Offalkalinder ?

### ISSUE THREAD

**Issue by Friesje** [pippyn/Home-Assistant-Sensor-Afvalbeheer#450]
Is it possible to add Offalkalinder [https://www.offalkalinder.nl/]

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by pippyn** [comment]
That is the address I meant. Can yiou give me an example postal code and number that works?

**Comment by Friesje** [comment]
For example 9104EB , number 16

**Comment by pippyn** [comment]
Added support in v5.2.17

Sample config:
```
afvalbeheer:
  - wastecollector: Offalkalinder
    resources:
      - restafval
      - gft
      - papier
    postcode: 9104EB
    streetnumber: 16
    printwastetypes: 1
    upcomingsensor: 1
```
