### ISSUE TITLE
Data is not loading mijnafvalwijzer

### ISSUE THREAD

**Issue by JeePee1982** [pippyn/Home-Assistant-Sensor-Afvalbeheer#451]
```yaml
afvalbeheer:
    wastecollector: MijnAfvalwijzer
    resources:
        - restafval
        - gft
        - papier
        - pmd
    postcode: 5171HC
    streetnumber: 40
    suffix: a                        # (optional)
    upcomingsensor: 1                # (optional)
    dateformat: '%d-%m-%Y'           # (optional)
    dateonly: 0                      # (optional)
    name: ""                         # (optional)
    nameprefix: 1                    # (optional)
    builtinicons: 1                  # (optional)
    dutch: 1                         # (optional)
```

this code doent fetch the data
