### ISSUE TITLE
Integration does not show any dates

### ISSUE THREAD

**Issue by Sweepr** [pippyn/Home-Assistant-Sensor-Afvalbeheer#455]
Integration does not show any data, any idea what i am doing wrong here?
It look like this on my dashboard:

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/2857865/1cb57791-0032-457c-9e19-ea9ce0feda05)

Yaml code:
```
type: entities
entities:
  - calendar.afvalbeheer_mijnafvalwijzer
  - sensor.mijnafvalwijzer_first_upcoming
  - sensor.mijnafvalwijzer_gft
  - sensor.mijnafvalwijzer_papier
  - sensor.mijnafvalwijzer_pmd
  - sensor.mijnafvalwijzer_restafval
  - sensor.mijnafvalwijzer_today
  - sensor.mijnafvalwijzer_tomorrow
```

Configuration.yaml

```
afvalbeheer:
    wastecollector: MijnAfvalwijzer
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1111AB
    streetnumber: 1
    suffix: a                        # (optional)
    upcomingsensor: 1                # (optional)
    dateformat: '%d-%m-%Y'           # (optional)
    dateonly: 0                      # (optional)
    name: ""                         # (optional)
    nameprefix: 1                    # (optional)
    builtinicons: 1                  # (optional)
    dutch: 0                         # (optional)
```

The card does not look like this:

![example](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/2857865/6031bde3-51b7-457e-879f-f78872e24c28)
