### ISSUE TITLE
No information

### ISSUE THREAD

**Issue by Rufes1989** [pippyn/Home-Assistant-Sensor-Afvalbeheer#456]
Cant get any information. Keeps showing “onbekend”

![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/157975889/020f9f4f-9e3e-43fa-a4bb-9d6f16fb5a87)

```
afvalbeheer:
  wastecollector: mijnafvalwijzer
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 1704MB
  streetnumber: 22
  suffix: a                        # (optional)
  upcomingsensor: 0                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 1                  # (optional)
  dutch: 1                         # (optional)
```
