### ISSUE TITLE
"Day" is missing with HVC PBD

### ISSUE THREAD

**Issue by Naobana** [pippyn/Home-Assistant-Sensor-Afvalbeheer#46]
PBD doesn't show the day of the pick-up date.

**- Not working: PBD**

![image](https://user-images.githubusercontent.com/33698556/76978612-36b26480-6937-11ea-9523-805cdc85b269.png)

**- Working: GFT**

![image](https://user-images.githubusercontent.com/33698556/76978773-6e211100-6937-11ea-8ae1-57ab5810c3e8.png)

Configuration:

```
  - platform: afvalbeheer
    wastecollector: HVC
    resources:
      - restafval
      - gft
      - papier
      - pbd
    postcode: 0000XX
    streetnumber: 24
    upcomingsensor: 0
    dateformat: '%d-%m-%Y'
    dateonly: 0
    name: ""
    nameprefix: 1
    builtinicons: 0
    dutch: 1
```

Thanks for your briljant hassio integration btw :-)
