### ISSUE TITLE
RecycleApp: My street is no longer recognized

### ISSUE THREAD

**Issue by JasperMaes** [pippyn/Home-Assistant-Sensor-Afvalbeheer#466]
Hi,

My street is no longer recognized since somewere today/yesterday (I didn't really notice until now) when using the RecycleApp waste collector. The error message I receive is: _Invalid response from server for street_id_. When I use the RecyleApp website it still works, when I use another street name from around the corner it also works. It's only my street that seems to be an issue. 

I'm running the latest version that was released today but also had the issue in the previous version (I upgraded in an attempt to fix the problem).

Do you have any idea what could be the cause? Maybe because it has a '-' in the name?

Kind regards,

Jasper

**Comment by pippyn** [comment]
Please share your config and an address to test with

**Comment by JasperMaes** [comment]
I've tried to disable as much as possible for testing. My address is: Sint-Michaelshof 8, postal code 1851. An address around the corner, oostvaartdijk 415 works without issues.

```
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 1851
  streetnumber: 8
  streetname: Sint-Michaelshof

```

**Comment by pippyn** [comment]
Did you try this:
```
afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 1851
  streetnumber: 8
  streetname: "Sint-Michaelshof"
```

**Comment by JasperMaes** [comment]
Thank you for the suggestion. Unfortunately it doesn't solve the problem.

**Comment by nathan-gs** [comment]
Exactly the same issue here, with an address in Ghent (zip: 9042)

**Comment by pippyn** [comment]
When you downgrade to to 5.2.8 does it work again?
I'll dive into this issue tomorrow

**Comment by nathan-gs** [comment]
(no hurry, the workaround of a neighboring street works well)

**Comment by nathan-gs** [comment]
Unfortunately a downgrade to 5.2.8 gives following error
`Invalid response from server for accessToken`

**Comment by pippyn** [comment]
There is a problem with their API. A dash in the street name is no longer accepted. There also seems no way to escape it in the code. However the full street name is not required. So the following config works as expected.

```
afvalbeheer:
  - wastecollector: RecycleApp
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1851
    streetnumber: 8
    streetname: Michaelshof
```
