### ISSUE TITLE
PMD changed to capitals?

### ISSUE THREAD

**Issue by Arbotje** [pippyn/Home-Assistant-Sensor-Afvalbeheer#470]
I ran into an issue, displaying the icon for pmd on my dashboard.
After updating to version 5.3.1, the custom icon I use in my config didn't load anymore.
I had to change the key value from pmd to PMD, in capitals.

I use gad as waste collector.

**Comment by pippyn** [comment]
Yes update 5.3.1 fixes the capitalization of the fractions. But it shouldn't affect the unique IDs.
How are you assigning the icon?

**Comment by Arbotje** [comment]
I have the code below in my card definitions. It worked using lowercase only before version 5.3.1. To get it working again I added an extra line with PMD.

      - type: picture-entity
        entity: sensor.gad_morgen
        name: Morgen
        state_image:
          gft: local/afvalwijzer/gad/gft.svg
          papier: local/afvalwijzer/gad/papier.svg
          restafval: local/afvalwijzer/gad/kliko-grijs-rest.svg
          pmd: local/afvalwijzer/gad/pmd.svg
          PMD: local/afvalwijzer/gad/pmd.svg
          Geen: local/afvalwijzer/gad/kliko-wit.svg

Fortunately, there is a workaround. It took me a while to find out what has changed.

**Comment by pippyn** [comment]
Ahh yes this will affect pmd also, it will become `PMD`. So your config will change to this:
```
 - type: picture-entity
    entity: sensor.gad_morgen
    name: Morgen
    state_image:
      GFT: local/afvalwijzer/gad/gft.svg
      Papier: local/afvalwijzer/gad/papier.svg
      Restafval: local/afvalwijzer/gad/kliko-grijs-rest.svg
      PMD: local/afvalwijzer/gad/pmd.svg
      Geen: local/afvalwijzer/gad/kliko-wit.svg
```
