### ISSUE TITLE
Limburg.NET possible API issue (or config. not sure anymore)

### ISSUE THREAD

**Issue by jayjayseal** [pippyn/Home-Assistant-Sensor-Afvalbeheer#472]
[The limburg.net API-proxy works as far as i can see. but still the sensors are unavailable.]

(https://limburg.net/api-proxy/public/afval-kalender/gemeenten/search?query=gingelom) gives a nisCode
```
afvalbeheer:
  wastecollector: Limburg.NET
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 3890
  streetname: xxx
  cityname: xxx
  streetnumber: x
  upcomingsensor: 1 # (optional)
  dateformat: "%d-%m-%Y" # (optional)
  dateonly: 0 # (optional)
  nameprefix: 1 # (optional)
  builtinicons: 0 # (optional)
  dutch: 1 # (optional)
```

**Comment by pippyn** [comment]
Please provide an address in your neighborhood for me to test with

**Comment by pippyn** [comment]
This config is working fine for me:
```
afvalbeheer:
  - wastecollector: Limburg.NET
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 3890
    streetname: Houtstraat
    cityname: Gingelom
    streetnumber: 2
    upcomingsensor: 1 # (optional)
    dateformat: "%d-%m-%Y" # (optional)
    dateonly: 0 # (optional)
    nameprefix: 1 # (optional)
    builtinicons: 0 # (optional)
    dutch: 1 # (optional)
```
![image](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/7591990/a0bfd311-5100-4309-a0c5-bd88935a55e3)
