### ISSUE TITLE
Afvalstoffendienstkalender stopped working

### ISSUE THREAD

**Issue by fschutter** [pippyn/Home-Assistant-Sensor-Afvalbeheer#477]
Since 7th of April all sensors of Afvalstoffendienstkalender changed to 'Unknown'.
![Screenshot 2024-04-10 085704](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/84066823/ab0dc1d2-d8a2-4a6e-b4f8-e8360ef9cf97)

Config:
```
afvalbeheer:
  wastecollector: Afvalstoffendienstkalender
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 5245AA
  dateformat: '%d-%m-%Y'
  dateonly: 1
  dayofweek: 0
  streetnumber: 11
  builtinicons: 1
  builtiniconsnew: 1
```
