### ISSUE TITLE
Deafvalapp api

### ISSUE THREAD

**Issue by JaySea77** [pippyn/Home-Assistant-Sensor-Afvalbeheer#479]
Deadvalapp api verandert de waarde van morgen en vandaag meerdere keren per dag. Doordat dit steeds gebeurt, kun je de waarde hiervan niet meer afvangen.
Zo was het eerst 'pmd, gft' en nu ineens 'GFT, PMD'. Vorige week was het 'Restafval, Gft' en enkele uren later 'Restafval, GFT'
De volgorde en het hoofdletter gebruik wijzigt steeds.

**Comment by pippyn** [comment]
What is your config?

**Comment by JaySea77** [comment]
afvalbeheer:
  wastecollector: DeAfvalApp
  resources:
    - restafval
    - gft
    - pmd
  postcode: XXXX99 {this is my actual postalcode}
  streetnumber: 99 {this is my actual home number}
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dateonly: 1
  alwaysshowday: 0
  printwastetypes: 0
  dateobject: 0
  name: ""
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 1

**Comment by pippyn** [comment]
Change your resources to the capitalization you want to make it consistent.
I would recommend this:

```
afvalbeheer:
  wastecollector: DeAfvalApp
  resources:
    - Restafval
    - GFT
    - PMD
  postcode: XXXX99 {this is my actual postalcode}
  streetnumber: 99 {this is my actual home number}
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dateonly: 1
  alwaysshowday: 0
  printwastetypes: 0
  dateobject: 0
  name: ""
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 1
```

Warming: This could change the unique entity id's in some cases
