### ISSUE TITLE
Something is blocking Home Assistant from wrapping up the start up phase

### ISSUE THREAD

**Issue by HammerNL89** [pippyn/Home-Assistant-Sensor-Afvalbeheer#488]
When I restarted my Home Assistant instance, I noticed the default info message on the lower left:
```
Starting Radio Browser, not everything will be available until it is finished.
```
took longer to disappear than normally.  When checking the logs I noticed the following:

```
The system is waiting for tasks: {<Task pending name='track point in utc time 2024-06-22 10:17:31.959174+00:00' coro=<WasteData.async_update() running at /config/custom_components/afvalbeheer/API.py:151> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]> cb=[set.remove()]>}
```
and eventually: 

```
Log details (WARNING)
Logger: homeassistant.bootstrap
Source: bootstrap.py:1046
First occurred: 12:22:49 (1 occurrences)
Last logged: 12:22:49

Setup timed out for bootstrap waiting on {<Task pending name='track point in utc time 2024-06-22 10:17:31.959174+00:00' coro=<WasteData.async_update() running at /config/custom_components/afvalbeheer/API.py:151> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]> cb=[set.remove()]>} - moving forward
```
my afvalbeheer config (didn't change):
```yaml
afvalbeheer:
  wastecollector: MijnAfvalwijzer
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: <my_postcode>
  streetnumber: <my_streetnumber>
  upcomingsensor: 1
  dutch: 1
  builtinicons: 1
  builtiniconsnew: 1
```

System info:
```
Core: 2024.6.4
Supervisor: 2024.06.0
Operating System: 12.4
Frontend: 20240610.1
Afvalbeheer: v5.3.5
```
I didn't update the custom integration for a while (afvalbeheer), but noticed an deprecation warning in the logs so updated to the latest one.
