### ISSUE TITLE
RWM no longer working with Mijnafvalwijzer.nl

### ISSUE THREAD

**Issue by Tijgerd** [pippyn/Home-Assistant-Sensor-Afvalbeheer#490]
I noticed I could no longer see my waste collection days in HA.
Further investigation led me to MijnAfvalwijzer.nl which no longer has a connection with RWM.
I mailed to RWM and got the response that they are no longer working with Mijnafvalwijzer.nl and that I should use the RWM app.

I asked RWM if there is an API available but they where not responding (yet)

**Comment by pippyn** [comment]
I'll have a look. Do you have an address for me to test with that works on https://rwm.nl/wanneer?

**Comment by Tijgerd** [comment]
6151BT nr 6 (can you confirm that you got this so I can remove it again :D )

**Comment by pippyn** [comment]
Just use RWM as a collector.
example:
```
afvalbeheer:
  - wastecollector: RWM
    resources:
      - Papier
      - PMD
      - Restafval
    postcode: 6151**
    streetnumber: *
```
