### ISSUE TITLE
No icons, only default HA ones

### ISSUE THREAD

**Issue by StarWing01** [pippyn/Home-Assistant-Sensor-Afvalbeheer#493]
Hi, 

Please keep in mind that I'm a HA noob :) I don't really know if it's an issue or simply a mistake from my side.
I'm currently migrating from Domoticz to HA and I found your repo. I'm adding it to my HA installation for use with ILVA waste collector (Oost-Vlaanderen, Belgium).

I made a std config and the dates are beeing collected and are correct for my location.
However, in HA, I don't see any of the icons that are available, or which I can see on the thread in the HA forums. The only ones I see are the default HA ones.

2nd, how can I get consistency in the dates? Some are showing the day before the date, other ones only the date.

![Naamloos](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/6688893/6748e0c4-bd2e-4518-9238-491089d0830a)

my cfg:
configuration.yaml
```
# Afvalbeheer
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
    - GFT
    - Papier
    - PMD
    - Restafval
    - Glas
    dutch: 1
    postcode: 9420
    streetnumber: XX
    streetname: XXXXXXXXX
    upcomingsensor: 1
    builtiniconsnew: 1
    dateformat: '%d-%m-%Y'
```

card:
```
type: custom:auto-entities
card:
  type: entities
  title: Afvalkalender
  state_color: false
  show_header_toggle: false
entities:
  - sensor.recycleapp_pmd
  - sensor.recycleapp_papier
  - sensor.recycleapp_glas
  - sensor.recycleapp_restafval
  - sensor.recycleapp_gft
sort:
  method: entity_id
  attribute: Sort-date
  reverse: true
  numeric: false
```

Thanks !

**Comment by pippyn** [comment]
HI @StarWing01 , welcome to HA.

Sure, just add these 2 lines to your config:
```
dayofweek: 0
builtinicons: 1
```

**Comment by pippyn** [comment]
BTW you are using the old way to implement the sensor. Use the new way to get calendar support.
Remove your config from your `sensor:` section and add it as a platform. It should look somewhat like this:
```
# Afvalbeheer
afvalbeheer:
  - wastecollector: RecycleApp
    resources:
    - GFT
    - Papier
    - PMD
    - Restafval
    - Glas
    dutch: 1
    postcode: 9420
    streetnumber: XX
    streetname: XXXXXXXXX
    upcomingsensor: 1
    builtiniconsnew: 1
    dateformat: '%d-%m-%Y'
    dayofweek: 0
    builtinicons: 1
```

**Comment by StarWing01** [comment]
I have no clue what you mean with your last post about platform :) But I'll google it.
I've changed my configuration.yaml file according to your suggestion. 
This solved the date issue, but still no icons :/

To be complete, I have installed through HACS, not manually, and applied the lastest update (v5.3.6).

**Comment by pippyn** [comment]
That is a bug.
But it should be fixed in v5.3.7

**Comment by StarWing01** [comment]
Icons fixed after last update. 
Remains: sorting by date.

**Comment by pippyn** [comment]
You can do that with a custom card. I use `auto-entities`, example:

```
card:
  show_header_toggle: false
  title: Afvalbeheer
  type: entities
filter:
  exclude:
    - state: unknown
  include:
    - entity_id: sensor.gft
    - entity_id: sensor.gftgratis
    - entity_id: sensor.papier
    - entity_id: sensor.pmd
    - entity_id: sensor.restafval
sort:
  method: attribute
  attribute: Sort_date
  reverse: false
type: custom:auto-entities
```

**Comment by StarWing01** [comment]
Fixed !

Latest card code:

```
type: custom:auto-entities
card:
  type: entities
  title: Afvalkalender
  state_color: false
  show_header_toggle: false
entities:
  - sensor.recycleapp_pmd
  - sensor.recycleapp_papier
  - sensor.recycleapp_glas
  - sensor.recycleapp_restafval
  - sensor.recycleapp_gft
sort:
  method: attribute
  attribute: Sort_date
  reverse: false
filter:
  exclude:
    - state: unknown
```

**Comment by xtiman** [comment]
Awesome ^^. Stumbled upon this thread when when looking for a fix for the missing icons. Reinstall of 'Afvalbeheer'  app did the trick. This custom card which makes sorting based on pick up is also quite nice. Thanks :D

**Comment by brommetje** [comment]
Same problem as above no icons (5.6.0) doing something wrong but what?

my config:

#
afvalbeheer:
  wastecollector: Avri
  name: 'avri'
  resources:
  - gft
  - papier
  - pmd
  postcode: 1234AA
  streetnumber: 1
  dutch: 1
  dayofweek: 0
  buildinicons: 0
  #builtiniconsnew: 1
  upcomingsensor: 1
  #dateformat: '%d-%m-%Y'
  dateonly: 0
#

Martin

**Comment by pippyn** [comment]
Set `buildinicons` to 1

**Comment by magin1** [comment]
Same problem with no icons. 
Redownloaded repo in hacs also with no fix

Configuration.Yaml

afvalbeheer:
  wastecollector: Omrin
  resources:
    - gft
    - papier
    - textiel
    - grofvuil
    - chemisch
    - sortibak
  postcode: 
  streetnumber: 
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 0
  name: ""
  nameprefix: 1
  builtinicons: 1
  dutch: 1
  dayofweek: 0

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by brommetje** [comment]
> Do you have an address for me to test with?

Avri 4147AW 10

**Comment by magin1** [comment]
> Do you have an address for me to test with?

No sorry private system.

But I deleted the afvalbeheer files though hacs and Redownloaded and now it works. Also added the new icons line and they look great.

**Comment by brommetje** [comment]
4147EG number 3

**Comment by brommetje** [comment]
> > Do you have an address for me to test with?
> 
> No sorry private system.
> 
> But I deleted the afvalbeheer files though hacs and Redownloaded and now it works. Also added the new icons line and they look great.

Not working for me, HA version 2025.2

#
afvalbeheer:
  wastecollector: Avri
  name: 'avri'
  resources:
  - gft
  - papier
  - pmd
  postcode: 4147EG
  streetnumber: 3
  dutch: 1
  dayofweek: 0
  buildinicons: 1
  #builtiniconsnew: 1
  upcomingsensor: 1
  #dateformat: '%d-%m-%Y'
  dateonly: 0
#

Martin

**Comment by pippyn** [comment]
@brommetje You spelled `builtinicons` wrong.

**Comment by brommetje** [comment]
> @brommetje You spelled `builtinicons` wrong.

Oops big finger, thanks @pippyn for your help it is working now.

**Comment by ErwinW2511** [comment]
@pippyn 
I seem to have the same issue, no icons.
I have already tries the options mentioned, rebooted the system, waited a couple of hours, but still no change.
Probarly something stupid i forgot to do ;-) Could you please advise? 

Version installed v5.6.2

Configuration.yaml
# Afvalbeheer
afvalbeheer:
  wastecollector: Reinis
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 3206GN
  streetnumber: 11
  upcomingsensor: 1           # (optional)
  dateformat: '%d-%m-%Y' # (optional)
  dateonly: 0                        # (optional)
  nameprefix: 1                    # (optional)
  builtiniconsnew: 1             # (optional)
  dutch: 1                             # (optional)

**Comment by pippyn** [comment]
@ErwinW2511 You are missing the option `builtinicons: 1`

```
afvalbeheer:
  - wastecollector: Reinis
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 3206GN
    streetnumber: 11
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    dateonly: 0
    nameprefix: 1
    builtinicons: 1
    builtiniconsnew: 1
    dutch: 1
```
