### ISSUE TITLE
Location Almere missing Rest+PMD

### ISSUE THREAD

**Issue by Osjuh** [pippyn/Home-Assistant-Sensor-Afvalbeheer#512]
Hi Team,

From next month Almere will make use of Rest+PMD, the PMD bin will be removed from the houses. 
When I look at the calendar in Home Assistant I see that Rest and PMD are missing from the calendar.

This is the code I currently use, and I'm not able to see what other resource I can use to get the Rest+PMD listed in my calendar.

```
afvalbeheer:
  wastecollector: Almere
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: Postcode
  streetnumber: streetnumber
  upcomingsensor: 1
  dateformat: "%d %b %Y"
  dateonly: 0
  alwaysshowday: 1
  dateobject: 0
  name: "waste"
  nameprefix: 1
  builtinicons: 1
  builtiniconsnew: 1
  disableicons: 0
  dutch: 0
```

See printscreens from the Gemeente Almere app and Home Assistant calendar.

![IMG_2007](https://github.com/user-attachments/assets/b6a3005e-4298-4385-9e00-5a1224843dfd)
<img width="1217" alt="Screenshot 2024-09-23 at 20 15 22" src="https://github.com/user-attachments/assets/72d9bb58-a680-4901-9a14-aba016cf64af">
