### ISSUE TITLE
Automatisation to change ligth color doesn't work

### ISSUE THREAD

**Issue by AntiMoon-ai** [pippyn/Home-Assistant-Sensor-Afvalbeheer#526]
Hello,

I try to switch a light from color depending what type of garbage it is the day after.
From the info that I found on the web. I programmed it correctly but it doesn't do anything.
Could you help me out and point out where in the yaml the problem is?
Thank you in advance 

```
alias: Test
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.restafval
    attribute: Days_until
    below: 1
    id: "1"
  - trigger: numeric_state
    entity_id:
      - sensor.pmd
    attribute: Days_until
    below: 1
    id: "2"
  - trigger: numeric_state
    entity_id:
      - sensor.papier
    attribute: Days_until
    below: 1
    id: "3"
conditions:
  - condition: state
    entity_id: switch.100201a6ed_2
    state: "on"
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - "1"
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              rgb_color:
                - 255
                - 0
                - 0
            target:
              entity_id: light.keuken_4
      - conditions:
          - condition: trigger
            id:
              - "2"
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              rgb_color:
                - 0
                - 0
                - 255
            target:
              entity_id: light.keuken_4
      - conditions:
          - condition: trigger
            id:
              - "3"
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              rgb_color:
                - 255
                - 255
                - 0
            target:
              entity_id: light.keuken_4
mode: single
```
