### ISSUE TITLE
date restafval incorrect

### ISSUE THREAD

**Issue by benutti** [pippyn/Home-Assistant-Sensor-Afvalbeheer#53]
sorry to bother you here now... 
after testing , I get wrong date for restafval:
ophaalkalender afval restafval
17-04-2020
ophaalkalender afval papier
17-04-2020
ophaalkalender afval pmd
24-04-2020

restafval should be 16-01-2020  (always on thursdays, p-k & pmd 3weelky on fridays)
(address is 8650 , Beukhoutstraat 38)

**Comment by pippyn** [comment]
What is your config?
For me it shows correct?
![image](https://user-images.githubusercontent.com/7591990/79209927-578dad00-7e44-11ea-9504-031cdd4d958f.png)
With this config:
```
  - platform: afvalbeheer
    wastecollector: ophaalkalender
    dateformat: '%d %b'
    nameprefix: False
    resources:
      - restafval
      - papier
      - pmd
    postcode: 8650
    streetname: Beukhoutstraat
    streetnumber: 38
    upcomingsensor: 1
    dutch: 1
```
