### ISSUE TITLE
Integration sensor all status Unavailable 

### ISSUE THREAD

**Issue by verhoevendanny** [pippyn/Home-Assistant-Sensor-Afvalbeheer#533]
After the update all sensors are unavailable except recycle today

**Comment by eclaassens** [comment]
Probably the same as https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/531

**Comment by ilias6006** [comment]
Same here

**Comment by elpantzo** [comment]
i changed the sensors of all to  sensor.hvc_gft_2

Seems like there are new sensors inplace

**Comment by pippyn** [comment]
Remove all the old sensors and restart HA and the names should be as they were

**Comment by MrHappy** [comment]
Did that, names are as they were.
The sensors all return 'unknown' though.

**Comment by zmstr** [comment]
Same happened for me. Manually removed all entries, I cleared all afvalbeheer lines in configuration.yaml, restarted HA so every trace was gone. Added lines of code back but after that my HA completely froze when I opened the dashboard with all the afvalbeheer sensors. I even had to do a hard reset of my raspberry pi to get it back up again. But after this update sensors like tomorrow or upcoming also have the "Invalid timestamp" as a value.

I tried reverting back to an older version in HACS (v5.4.3, when everything was working) but I get the error:

`The version v5.4.3 for this integration can not be used with HACS.`

Any an idea how I can downgrade and what might the causing the issue in the new version?

**Comment by pippyn** [comment]
@zmstr what is your config?

**Comment by zmstr** [comment]
```yaml
afvalbeheer:
  - wastecollector: RD4
    resources:
      - restafval
      - gft
      - papier
      - pmd
      - kerstbomen
      - best-tas
    postcode: 6374PH
    streetnumber: 56
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    nameprefix: 1
    dutch: 1
    dateonly: 1
    dateobject: 1
    printwastetypes: 0
    name: mondriaanstraat
```
