### ISSUE TITLE
Ophaalkalender sensor missing a collection

### ISSUE THREAD

**Issue by phdelodder** [pippyn/Home-Assistant-Sensor-Afvalbeheer#54]
I just installed it and compared it to the "ophaal kalender" and it seems that it miss the next collection: 

Image of the sensor: 
![image](https://user-images.githubusercontent.com/7259755/79207945-aa199a00-7e41-11ea-8e68-c7c0a51ea0ea.png)

Image of the calendar: 
![image](https://user-images.githubusercontent.com/7259755/79207845-86565400-7e41-11ea-9924-d20cf3b993a2.png)

Config: 
```
- platform: afvalbeheer
  wastecollector: ophaalkalender
  resources:
    - restafval
    - papier
    - pmd
    - gft
  postcode: !secret ophaalkalender_postcode
  streetname: !secret ophaalkalender_streetname
```

Version using is 3.1.0
