### ISSUE TITLE
problem with custommapping

### ISSUE THREAD

**Issue by bartve66** [pippyn/Home-Assistant-Sensor-Afvalbeheer#545]
I have a problem with custommapping. In my configuration.yaml I have:

...
    resources:
      - restafval
      - gft
      - papier
      - pmd
    custommapping:
      restafval: rest
      papier: pap
...

Before I entered de custommapping part the sensor read '4 jan: PMD, Restafval', and now it reads '4 jan: PMD' (I tried both 'restafval' and  'Restafval' in the custommaping part).

**Comment by pippyn** [comment]
What are you trying to do?

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by bartve66** [comment]
ehh ... how would that work? what kind of addres do you need? my HA access, or file level access? it is not massively secured by firewalls, logins, and the lot for nothing ....

**Comment by pippyn** [comment]
No a home address in your neighborhood, so I can see what the fractions are named in the API

**Comment by bartve66** [comment]
Aha! Still a bit private: I sent you a DM on the HA forum (read that in another issue). Thanks!

**Comment by pippyn** [comment]
I understand, no problem.
This config should work:
``` 
afvalbeheer:
  - wastecollector: DAR
    resources:
      - REST
      - GFT
      - PMD
      - PAP
      - KERST
    postcode: 1111AA
    streetnumber: 1
    upcomingsensor: 1
    custommapping:
      Restafval: REST
      GFT: GFT
      PMD: PMD
      Papier: PAP
      Kerstbomen: KERST
```
