### ISSUE TITLE
PreZero: eerstvolgende is 'geen', GFT is de eerstvolgende (07-01-2025).

### ISSUE THREAD

**Issue by Calimerorulez** [pippyn/Home-Assistant-Sensor-Afvalbeheer#547]
Hi :)

Sinds enkele dagen is de PreZero 'eerstvolgende' sensor 'geen', terwijl de eerstvolgende in mijn geval GFT is, die wel een datum heeft (07-01-2025).

Postcodegebied is 3755.

**Comment by pippyn** [comment]
What is your complete config?

**Comment by Calimerorulez** [comment]
```
afvalbeheer:
  wastecollector: PreZero
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 3755XX
  streetnumber: XX
  upcomingsensor: 1                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 0                  # (optional)
  dutch: 1                         # (optional)
```

I redacted the full zipcode and housenumber.
