### ISSUE TITLE
Missing waste fraction - keukenafval for Limburg.net

### ISSUE THREAD

**Issue by DriesA** [pippyn/Home-Assistant-Sensor-Afvalbeheer#550]
Hi Pippyn,

Thanks for creating this custom component. I really love it!

I think for Limburg.net, a type of waste fraction is missing.

When I check the [waste calendar 1](https://www.limburg.net/afvalkalender) on [Limburg.Net](http://limburg.net/), I see that they will collect “keukenafval” next Friday:

When I print the waste types, I see keukenafval is not listed.

Config:

`    wastecollector: Limburg.NET
    resources:
      - restafval
      - gft
      - papier
      - pmd
      - textiel
#      - keukenafval
      - tuinafval
    postcode: 3590
    cityname: Diepenbeek
    streetname: Oude Baan
    streetnumber: 4
#    printwastetypes: 1
    upcomingsensor: 1                # (optional)
    dateformat: '%d-%m-%Y'           # (optional)
    dateonly: 0                      # (optional)
    dayofweek: 1
    dateobject: 1
    dutch: 1                         # (optional)
    builtinicons: 1
    builtiniconsnew: 1`

**Comment by pippyn** [comment]
Use this config:
```
afvalbeheer:
  - wastecollector: Limburg.NET
    resources:
      - restafval
      - gft
      - papier
      - pmd
      - textiel
      - keukenafval
      - tuinafval
    postcode: 3590
    cityname: Diepenbeek
    streetname: Oude Baan
    streetnumber: 4
    # printwastetypes: 1
    upcomingsensor: 1 # (optional)
    dateformat: "%d-%m-%Y" # (optional)
    dateonly: 0 # (optional)
    dayofweek: 1
    dateobject: 1
    dutch: 1 # (optional)
    builtinicons: 1
    builtiniconsnew: 1
    custommapping:
      Keukenafval: Keukenafval
```
