### ISSUE TITLE
Almere broken

### ISSUE THREAD

**Issue by robinkesting** [pippyn/Home-Assistant-Sensor-Afvalbeheer#553]
Hi!

I use this integration and worked like a charm! Only thing that is broken now is Almere. Recently they removed plastic bins. Restafval and plastic are now combined. 

I see 'Onbekend' on the restafval sensor and plastic sensor. How can I fix this or is this something that needs to be changed in the integration?

<img width="510" alt="Scherm­afbeelding 2025-01-15 om 10 40 07" src="https://github.com/user-attachments/assets/1a36ad76-cdd3-4a89-a543-6e622269baf5" />

**Comment by robinkesting** [comment]
```
# Afvalbeheer configuratie
afvalbeheer:
  wastecollector: Almere
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 1328DE
  streetnumber: 30
  upcomingsensor: 1
  dateformat: '%d %B (%A)'
  dateonly: 0
  dayofweek: 0
  nameprefix: 1
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 1
```

**Comment by pippyn** [comment]
You have your fractions wrong..
This config works:
```
afvalbeheer:
  - wastecollector: Almere
    resources:
      - GFT
      - Papier
      - PMD-Restafval
    postcode: 1328DE
    streetnumber: 30
    upcomingsensor: 1
    dateformat: "%d %B (%A)"
    dateonly: 0
    dayofweek: 0
    nameprefix: 1
    builtinicons: 1
    builtiniconsnew: 1
    dutch: 1
```
