### ISSUE TITLE
No waste data found

### ISSUE THREAD

**Issue by JohanKrab** [pippyn/Home-Assistant-Sensor-Afvalbeheer#560]
After update HACS no wast data found.

**Comment by pippyn** [comment]
What is your config?

**Comment by MaxMommersteeg** [comment]
Don't want to hijack this issue. But my issue correlates with the description and title of this issue.

My configuration:
```yaml
afvalbeheer:
  wastecollector: MijnAfvalwijzer
  resources:
    - gft
    - papier
    - pmd
  postcode: 1111AA // Not my actual postalcode, but real one used to work with this waste collector a couple of weeks ago
  streetnumber: 16
  printwastetypes: 1
  upcomingsensor: 1
  dutch: 1
```

**Comment by pippyn** [comment]
I do need a working postcode and streetnumber

**Comment by pippyn** [comment]
Nieuwkuijk doesn't use `MijnAfvalwijzer`, they use `Afvalstoffendienstkalender`. So this config will work:
```
afvalbeheer:
  - wastecollector: Afvalstoffendienstkalender
    resources:
      - papier
    postcode: 5253CB
    streetnumber: 12
    printwastetypes: 1
    upcomingsensor: 1
    dutch: 1
```
