### ISSUE TITLE
Hellendoorn

### ISSUE THREAD

**Issue by Resu4aidua** [pippyn/Home-Assistant-Sensor-Afvalbeheer#564]
Hoi Pippyn,

Ik probeer de afval kalender toe te voegen aan HA.
Uit 1 vd issues heb ik het voorbeeld gehaald. Deze laat netjes papier zien voor bepaalde datums.

Onderstaande config laat géén  datums zien. Ook niet na herstart HA.
Wat is hier de fout?

Gr. Peter

```
afvalbeheer:
  - wastecollector: Hellendoorn
    resources:
      - papier
    postcode: 7442TD
    streetnumber: 18
    printwastetypes: 1
    upcomingsensor: 1
    dutch: 1
```

**Comment by pippyn** [comment]
This config works fine:
```
afvalbeheer:
  - wastecollector: Hellendoorn
    resources:
      - GFT
      - Papier
      - PMD
      - Restafval
    postcode: 7442TD
    streetnumber: 18
    printwastetypes: 0
    upcomingsensor: 1
    dutch: 1
```
![Image](https://github.com/user-attachments/assets/1f191b9e-844d-45ab-bf4c-7786ef83049a)
