### ISSUE TITLE
Bug in calculation days until (Limburg.net)

### ISSUE THREAD

**Issue by Neijwiert** [pippyn/Home-Assistant-Sensor-Afvalbeheer#566]
Hi,

I'm using the limburg.net provider and there is something wrong with the days until calculation.  See the 'Papier' sensor in Home Assistant below (date of writing is February, 19th, 2025):

![Image](https://github.com/user-attachments/assets/7a1f3d14-fe04-49a6-9cb2-75792d9be90e)

As you can see the date is actually correct, but the 'Days_until' attribute is incorrect (being 1). Using Fiddler I inspected what the actual returned JSON is from the API and it is as follows:
`
{
            "type": "Huis-aan-huis-ophaling",
            "category": "Papier \u0026 karton",
            "date": "2025-02-19T08:38:35+01:00",
            "title": "Papier \u0026 karton",
            "description": null,
            "time": null,
            "location": null,
            "detailUrl": "https:\/\/limburg.net\/fractie\/papier-karton",
            "display": {
                "code": 1,
                "reden": ""
 }
`

Tracing through the code implementation it seems that the date is correctly parsed, excpet when it comes to calculating the difference which is located in 'sensor.py' line 187:
` date_diff = (collection.date - datetime.now()).days + 1`

What is the reason that a +1 is hardcoded here? Is that applicable for some waste providers? For Limburg.net this will always return a faulty offset of 1 day.

**Comment by pippyn** [comment]
What is your config? including an address to test with

**Comment by pippyn** [comment]
Sure:
https://community.home-assistant.io/u/pippyn/

**Comment by Neijwiert** [comment]
I think my account is too new (just created it) to be able to message you there. I joined the Home Assistant discord, what is your handle there (if you have one)?

**Comment by pippyn** [comment]
I'm not on the discord. You can also share a random address in your neighborhood

**Comment by Neijwiert** [comment]
Wevinnestraat 5, Diest (appears to have same collection date)

**Comment by pippyn** [comment]
And your config?

**Comment by Neijwiert** [comment]
```
afvalbeheer:
  - wastecollector: Limburg.NET
    resources:
      - restafval
      - papier
      - pmd
      - tuinafval
      - textiel
    postcode: 3290
    streetnumber: 5
    streetname: wevinnestraat 
    cityname: diest
    dutch: 1
    builtinicons: 1
    builtiniconsnew: 1
```

Actual address changed to the fake one
