### ISSUE TITLE
Omrin only one value

### ISSUE THREAD

**Issue by YouSeeNiek** [pippyn/Home-Assistant-Sensor-Afvalbeheer#567]
Hi,

I tried installing the integration but i am only getting one value (grofvuil)
Any ideas on how to get the other 3?
<img width="453" alt="Image" src="https://github.com/user-attachments/assets/557792e9-966b-447f-8fc3-67a067dbd8eb" />
<img width="873" alt="Image" src="https://github.com/user-attachments/assets/34e9c42e-83cf-4f2b-bb14-0585a96e632a" />

configuration.yaml:

afvalbeheer:
  wastecollector: Omrin
  resources:
    - restafval
    - gft
    - grofvuil
    - takken
  postcode: 9981AP
  streetnumber: 70

Not my real adress but close enough that they take the same route.

**Comment by pippyn** [comment]
This address had no collections according to https://www.omrin.nl/zelf-regelen/afvalkalender

**Comment by YouSeeNiek** [comment]
Can you try with streetnumber 76?

**Comment by pippyn** [comment]
This config works fine:

```
afvalbeheer:
  - wastecollector: Omrin
    resources:
      - Groene container
      - Grofvuil
      - Restafvalcontainer
      - Snoeiafval
    postcode: 9981AP
    streetnumber: 76
    printwastetypes: 1
```
