### ISSUE TITLE
No waste data found RMN

### ISSUE THREAD

**Issue by raymajor** [pippyn/Home-Assistant-Sensor-Afvalbeheer#568]
Hello the intergration RMN is not working anymore.
SUEZ & GAD is working fine.

The Config:
```
- platform: afvalbeheer
    wastecollector: RMN
    resources:
      - restafval
      - gft
      - pmd
      - papier
    postcode: 3761HA
    streetnumber: 11
    upcomingsensor: 1 
    dateformat: '%d-%m-%Y'
    dateonly: 0
    dateobject: 0
    name: 'RMN'
    nameprefix: 0 
    builtinicons: 1
    builtiniconsnew: 1
    disableicons: 0
    dutch: 1 
```
