### ISSUE TITLE
No waste data found RMN

### ISSUE THREAD

**Issue by Heldenmar** [pippyn/Home-Assistant-Sensor-Afvalbeheer#581]
my config is:
```
afvalbeheer:
wastecollector: RMN
resources:
- restafval
- gft
- papier
- pmd
postcode: ******
streetnumber: *
suffix: a 
upcomingsensor: 1 
dateformat: '%d-%b' 
dateonly: 1
name: "" 
nameprefix: 0
builtinicons: false 
dateobject: 1
dutch: 0 
printwastetypes: 1
```
today after a reboot it stopped working.

![Image](https://github.com/user-attachments/assets/60d046ee-2d84-440e-b892-abb504cb0bed)

**Comment by pippyn** [comment]
Do you have an address for me to test with?

**Comment by pippyn** [comment]
This works fine for me:
```
afvalbeheer:
  - wastecollector: RMN
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 3762XP
    streetnumber: 6
    upcomingsensor: 1
    dateformat: "%d-%b"
    dateonly: 1
    name: ""
    nameprefix: 0
    builtinicons: false
    dateobject: 1
    dutch: 0
    printwastetypes: 1
```

![Image](https://github.com/user-attachments/assets/0d4bc344-cea7-4de7-9eb5-a4df047afb7c)
