### ISSUE TITLE
Omrin: restafval does not resolve

### ISSUE THREAD

**Issue by caspar8412** [pippyn/Home-Assistant-Sensor-Afvalbeheer#582]
Hi,
As a HA neewbie, I rely on the great work of others. To complete my home dashboard I like to add your Afvalbeheer integration for company Omrin. _GFT_ and _papier_ resolve fine but _restafval_ doesn’t.

![Image](https://github.com/user-attachments/assets/d9161aba-a717-4db9-8df1-a8b079e6138a)

My configuration is:

afvalbeheer:
  wastecollector: Omrin
  resources:
    - restafval
    - gft
    - papier
  postcode: 8412TD
  streetnumber: 14
  upcomingsensor: 1                # (optional)
  dateformat: '%d-%m-%Y'           # (optional)
  dateonly: 0                      # (optional)
  name: ""                         # (optional)
  nameprefix: 1                    # (optional)
  builtinicons: 0                  # (optional)
  builtiniconsnew: 1               # (optional)
  dutch: 1                         # (optional)

Thanks if you can help.

**Comment by pippyn** [comment]
If you use the option `printwastetypes`, you can see that `restafval` is not supported by your waste collector.
This config should work fine though:
```
afvalbeheer:
  - wastecollector: Omrin
    resources:
    - GFT
    - Grofvuil
    - Papier
    - Snoeiafval
    - Sortibak
    - Textiel
    postcode: 8412TD
    streetnumber: 14
    upcomingsensor: 1 # (optional)
    dateformat: '%d-%m-%Y' # (optional)
    dateonly: 0 # (optional)
    name: "" # (optional)
    nameprefix: 1 # (optional)
    builtinicons: 0 # (optional)
    builtiniconsnew: 1 # (optional)
    dutch: 1 # (optional)
```
