### ISSUE TITLE
MijnAfvalwijzer en GFT Restafval

### ISSUE THREAD

**Issue by sjaakbremmers** [pippyn/Home-Assistant-Sensor-Afvalbeheer#586]
Gft en Restafval wordt voor Mijnafvalwijzer niet getoond. De optie printwastetypes laat deze idd niet zien. Wanneer ik de HA integratie Afvalwijzer gebruik, krijg ik het wel tezien wat is het verschil?

```
  - wastecollector: MijnAfvalwijzer
    resources:
    - restafval
    - gft
    - papier
    - pmd
    postcode: 6061BB
    streetnumber: 46
    upcomingsensor: 1                # (optional)
    dateformat: '%d-%m-%Y'           # (optional)
    dateonly: 0                      # (optional)
    dateobject: 0                    # (optional)
    dayofweek: 1                     # (optional)
    name: ''                         # (optional)
    nameprefix: 1                    # (optional)
    builtinicons: 0                # (optional)
    dutch: 1
    builtiniconsnew: 1
    printwastetypes: 1
```
