### ISSUE TITLE
First upcoming empty at Omrin with Sortibak

### ISSUE THREAD

**Issue by fbloemhof** [pippyn/Home-Assistant-Sensor-Afvalbeheer#588]
It seems the 'Sortibak' is not recognized completely as a waste type / fraction? When the sortibak is next, the next upcoming sensor is empty.

Also it has no (new) icon, this was mentioned before in other issues. 

It is pretty much the same as 'restafval', would it be possible to register it as an alias or something treat it like that?

**Comment by pippyn** [comment]
What is your config? With an address for testing

**Comment by fbloemhof** [comment]
```
afvalbeheer:
  wastecollector: Omrin
  resources:
    - sortibak
    - gft
    - papier
  postcode: 9244CR
  streetnumber: 82
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  dateonly: 0
  nameprefix: 1
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 1
```
