### ISSUE TITLE
All sensors reporting "unknown" for Afvalwijzer since latest update

### ISSUE THREAD

**Issue by jbouter** [pippyn/Home-Assistant-Sensor-Afvalbeheer#590]
Hi 👋🏻 ,

I've not done any configuration changes, only performed updates, and all sensors are now reporting "unknown" - whilst they used to be working before.

I am using version v5.6.6, installed through HACS

From the logs:

```
2025-06-14 23:03:36.114 ERROR (MainThread) [custom_components.afvalbeheer.API] No Waste data found!
```

Configuration is as follows:

```yaml
---
# Afvalbeheer config
afvalbeheer:
  - wastecollector: MijnAfvalwijzer
    printwastetypes: 1
    resources:
      - restafval
      - gft
      - papier
    postcode: 9753BE
    streetnumber: 23
    upcomingsensor: 1
    dateformat: '%Y-%m-%d'
    dateonly: 1
```

If I check with Afvalwijzer, I do get data:
https://www.mijnafvalwijzer.nl/nl/9753BE/23/
