### ISSUE TITLE
Feature Request: Add extra option to dateonly

### ISSUE THREAD

**Issue by skank01** [pippyn/Home-Assistant-Sensor-Afvalbeheer#61]
When i set dateonly to 0, you have the days before the date, if i set it to 1 , you dont get the date.
Is it possible to add a third option?:

I would like to have tomorrow or today without the date, but when its further away, i would be nice to have only the date (and not the day with it)…

**Comment by pippyn** [comment]
In version 4.1.4 there is a new option added: `dayofweek`.
By default this option is 1, but if you set this option to 0 the days of the week will not be added to the date. The prefix today and tomorrow are not affected.
(note: dateonly should **not** be 1)

Example:
```
  - platform: afvalbeheer
    wastecollector: ******
    resources:
      - pmd
    postcode: ******
    streetnumber: *
    dayofweek: 0
```

Could you please test if it works as you expected?
