### ISSUE TITLE
Adding Twente Milieu to this great addon

### ISSUE THREAD

**Issue by Bha-Eastbridge** [pippyn/Home-Assistant-Sensor-Afvalbeheer#74]
Can you please add support for twente milieu.
They have a api http://twentemilieuapi.ximmio.com/
Thanks!!

**Comment by pippyn** [comment]
Yes I can, I think. Do you have a postcode and streetnumber for me to test with?

**Comment by pippyn** [comment]
Can you test the beta version?
Install the component and then replace the contents of sensor.py with this version:
https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/TwenteMilieu/custom_components/afvalbeheer/sensor.py
Your config should look something like:
```
- platform: afvalbeheer
  wastecollector: twentemilieu
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 7533WS
  streetnumber: 47
```
