### ISSUE TITLE
Rova api?

### ISSUE THREAD

**Issue by gerthass** [pippyn/Home-Assistant-Sensor-Afvalbeheer#76]
hi pippyn,

Can you maybe check if the rova api can be added again?

**Comment by pippyn** [comment]
Yes I can. WIll add it this week

**Comment by pippyn** [comment]
Can you test a beta?
replace the contents of sensor.py with this:
https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/Rova/custom_components/afvalbeheer/sensor.py

Config:
```
- platform: afvalbeheer
  wastecollector: Rova
  resources:
    - gft
  postcode: ******
  streetnumber: *
```
